### ISSUE TITLE
[Feature request] MQTT external detector

### ISSUE THREAD

**Issue by CrashOverride-Git** [blakeblackshear/frigate#3586] opened 2022-08-04 12:20 UTC
Hello, 
it would to know if you can add the support for "generic external detectors", for example, a boolean input (ex. from the MQTT server) to trigger the recordings and snapshots.

It would be great if Frigate could start start recording simply using a signal from one of the zigbee motion sensor I have around the house (monitored by Home Assistant).

Ok a motion sensor could be less accurate than the cpu or a google coral and can create false positives but it consume less energy and it is faster. 
I am asking that because find a google TPU (at is real price) is very hard these days since there is a worldwide lack of components. 
Using a generic external detector is a cheap and easy alternative, especially for home users

Thanks

**Comment by NickM-27** [comment] 2022-08-04 12:31
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1063

**Closed** 2022-09-05 12:13 UTC
Labels: enhancement
