### ISSUE TITLE
Fallback to CPU

### ISSUE THREAD

**Issue by B0ndo2** [blakeblackshear/frigate#12517] opened 2024-07-19 17:14 UTC
I have a coral TPU which was failing frequently (I think it is faulty) and when it fails Frigate stops working.
I added CPU in the configuration and it looks like the CPU picks up the load when the TPU fails and until it comes back.

Is it possible to add more than one device and use priorities and fallback ?

**Comment by NickM-27** [comment] 2024-07-19 17:15
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2904

**Closed by NickM-27** 2024-07-19 17:15 UTC
Labels: duplicate, enhancement
