### ISSUE TITLE
Camera cover/blind detection

### ISSUE THREAD

**Issue by evolucja** [blakeblackshear/frigate#5804] opened 2023-03-22 14:58 UTC
Hi, I had a case that someone simply covered the camera with some clothing so it became blind.

Is there any chance to implement a detection algorithm for such cases to prevent moving or masking the camera?

Simple movement/people detection is not enough as the camera is in a place with constant movement, people walking through etc.

Thanks

**Comment by NickM-27** [comment] 2023-03-22 15:00
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1793 feel free to leave additional comments there and support with a 👍

**Closed** 2023-03-22 15:00 UTC
Labels: duplicate, enhancement
