### ISSUE TITLE
[Config Support]: Adding a blur filter on a video stream

### ISSUE THREAD

**Issue by bdherouville** [blakeblackshear/frigate#6048] opened 2023-04-13 16:03 UTC
### Describe the problem you are having

Hi,

I try to add the following video filter to blur part of the video but it makes the video stream unavailable.

-filter_complex "[0:v]crop=200:200:400:200[cropped];[0:v]crop=200:200:600:400[blurred_crop];[blurred_crop]boxblur=10[blurred];[blurred][cropped]overlay=600:400"

(I crop the date/time, blur the part and paste back the datetime over the blurred)

  my_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy 
        detect: '-vf scale=1280:720,[0:v]crop=200:200:400:200[cropped];[0:v]crop=200:200:600:400[blurred_crop];[blurred_crop]boxblur=10[blurred];[blurred][cropped]overlay=600:400 -f rawvideo -pix_fmt yuv420p '
      inputs:

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
my_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy 
        detect: '-vf scale=1280:720,[0:v]crop=200:200:400:200[cropped];[0:v]crop=200:200:600:400[blurred_crop];[blurred_crop]boxblur=10[blurred];[blurred][cropped]overlay=600:400 -f rawvideo -pix_fmt yuv420p '
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_my_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/rtsp_my_cam_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
```

### Relevant log output

```shell
2023-04-13 15:02:19.470549513  [INFO] Starting Frigate...
2023-04-13 15:02:20.302869394  [2023-04-13 17:02:20] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-04-13 15:02:20.337425326  [2023-04-13 17:02:20] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-04-13 15:02:20.337552855  [2023-04-13 17:02:20] peewee_migrate                 INFO    : Starting migrations
2023-04-13 15:02:20.341090200  [2023-04-13 17:02:20] peewee_migrate                 INFO    : There is nothing to migrate
2023-04-13 15:02:20.355543410  [2023-04-13 17:02:20] detector.coral1                INFO    : Starting detection process: 587
2023-04-13 15:02:20.394371236  [2023-04-13 17:02:20] detector.coral2                INFO    : Starting detection process: 589
2023-04-13 15:02:20.394461465  [2023-04-13 17:02:20] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
2023-04-13 15:02:20.394499377  [2023-04-13 17:02:20] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:1
2023-04-13 15:02:20.399798851  [2023-04-13 17:02:20] frigate.app                    INFO    : Output process started: 591
2023-04-13 15:02:20.399885894  [2023-04-13 17:02:20] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-04-13 15:02:20.399920189  [2023-04-13 17:02:20] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

**Comment by NickM-27** [comment] 2023-04-13 16:04
you need to include the logs otherwise there is on way to see what the problem is. Also, you should remove the `'` characters

**Comment by bdherouville** [comment] 2023-04-13 16:07
The relevant logs are there :
2023-04-13 16:06:44.908045871  [2023-04-13 18:06:44] frigate.video                  ERROR   : entree: Unable to read frames from ffmpeg process.
2023-04-13 16:06:44.908110483  [2023-04-13 18:06:44] frigate.video                  ERROR   : entree: ffmpeg process is not running. exiting capture thread...

**Comment by bdherouville** [comment] 2023-04-13 16:20
Apologize, too much info and I don't want to leak sensitive. BUT I have the following error.
Before it was just worse, jour suggestion to remote the quotes helped me. Thanks. Now i'm with ffmpeg issues.

2023-04-13 16:19:20.225394434  [2023-04-13 18:19:20] watchdog.entree                ERROR   : Ffmpeg process crashed unexpectedly for entree.
2023-04-13 16:19:20.225629605  [2023-04-13 18:19:20] watchdog.entree                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-04-13 16:19:20.225835903  [2023-04-13 18:19:20] ffmpeg.entree.detect           ERROR   : [AVFilterGraph @ 0x55792f27df00] Too many inputs specified for the "crop" filter.

**Comment by NickM-27** [comment] 2023-04-13 16:24
assuming you didn't want to close the issue. where did you get your crop format from? error seems pretty clear it is not the correct format

**Comment by bdherouville** [comment] 2023-04-13 17:05
Thanks @NickM-27 ! My main issue was the quotes that prevented any filter to apply. Now I'm almosd done.

The filter intend to crop the datetime, blur the region the paste the cropped datetime on top of the blurred region.

The regions needs to be fixed but this "technically works"

detect:  -filter_complex scale=1280:720;[0:v]crop=510:45:726:30[cropped];[0:v]crop=632:165:652:1[blurred_crop];[blurred_crop]boxblur=10[blurred];[0:v][blurred]overlay=652:1[blur1];[blur1][cropped]overlay=726:30 -f rawvideo -pix_fmt yuv420p

**Comment by bdherouville** [comment] 2023-04-13 17:22
Here is the filter and the result :+1: 
detect:  -filter_complex [0:v]crop=287:28:395:23[cropped];[0:v]crop=353:145:350:1[blurred_crop];[blurred_crop]boxblur=10[blurred];[0:v][blurred]overlay=350:1[blur1];[blur1][cropped]overlay=395:23[final];[final]scale=1280:720 -f rawvideo -pix_fmt yuv420p

![image](https://user-images.githubusercontent.com/13697064/231836385-b4dd57cd-df46-4a03-9d57-63837350fe80.png)

**Closed** 2023-04-13 17:29 UTC
Labels: support, triage
