### ISSUE TITLE
Add optional description field for event & http endpoint to set

### ISSUE THREAD

**Issue by irakhlin** [blakeblackshear/frigate#8844] opened 2023-12-03 18:54 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to set an additional "description" field for a specific event using the HTTP API and have it stored in the frigate db so it can be shown in the UI. 

**Describe the solution you'd like**
I am proposing a simple solution of proving an http api endpoint: POST /api/events/<id>/description that accepts a simple json:
`
{
"description": "this is what is happening in the video"
}
`
Some minor changes could be made to the UI to optionally show this in the event viewer. 
I have made a first pass at this on [my branch](https://github.com/irakhlin/frigate/commit/9b1f1ac493aa6d618c8f7a919e897c88a4c55e20) along with the tests and doc changes. As you can see from the screenshot however, I am not very great with the UI component. :
![image](https://github.com/blakeblackshear/frigate/assets/12637936/879624aa-7f45-42a7-aa9f-1c50ef1039a1)

**Describe alternatives you've considered**
I have attempted to use the sub_label endpoint to achieve this, unfortunately it seems only a single sub_label can be set on the event which is already being used in my case, to identify the person in an event. Additionally the field has a max char count of ~100, which can make generating a meaningful description difficult. 

**Additional context**
These proposed changes are connected to another project that is using triggered frigate events along with GPT4-vision to generate human readable and text based descriptions of the clip, [my WIP branch](https://github.com/irakhlin/amblegpt) can be found here. This however can be used with just about any multimodal models as they become more common and available.

**Comment by NickM-27** [comment] 2023-12-03 18:57
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3876

**Closed** 2023-12-03 18:57 UTC
Labels: duplicate, enhancement
