### ISSUE TITLE
Mobile app and scrub for recordings

### ISSUE THREAD

**Issue by Zandiexoder** [blakeblackshear/frigate#8508] opened 2023-11-06 23:40 UTC
**Describe what you are trying to accomplish and why in non-technical terms**
I want to be able to scrub through my footage in a timeline view. I believe that not having scrub is a major gap in the functionality in Frigate. (Of course this would only be used if 24/7 recording is on). I would like to be able to access the footage through a Frigate mobile that works better than the one size fits all web app in the home assistant app.

**Describe the solution you'd like**
A scrub similar to other home security apps from companies such: Nest, Scrypted and TP-Link (And many others) and the ability to view this footage through a Frigate camera. 

**Describe alternatives you've considered**
I looked at Scrypted, an open source video integration platform that has a NVR plugin with a high functionality timeline and scrub feature. The app for Scrypted also seems to work well on iPhone for viewing footage. I also like that it has better connection options to Alexa, Google home and homekit. I decided against switching over because I enjoy Frigate's advanced detection features and the abilityto send recordings to a different device (Server) through home assistant which Scrypted cannot do to my knowledge.

**Comment by NickM-27** [comment] 2023-11-06 23:41
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/2230

**Closed** 2023-11-06 23:43 UTC
Labels: duplicate, enhancement
