### ISSUE TITLE
Detect spiderwebs

### ISSUE THREAD

**Issue by sowbug** [blakeblackshear/frigate#12639] opened 2024-07-26 19:00 UTC
Spiders love to build webs in front of some of my outdoor cameras. The webs are invisible during the day when I might be looking at the live feed, but they completely obscure the image at night.

It would be really cool if the default model recognized obscuring webs. Then I could create a Home Assistant alert to tell me it's time to clean the cameras.

**Comment by NickM-27** [comment] 2024-07-26 19:03
I don't think spider web detection really makes sense as an object detection model, but there should be other ways to detect things like that, bugs, etc. 

This is functionally a duplicate of https://github.com/blakeblackshear/frigate/issues/67

**Closed by NickM-27** 2024-07-26 19:03 UTC
Labels: duplicate, enhancement
