### ISSUE TITLE
Mass deletion features for events

### ISSUE THREAD

**Issue by nsprawling** [blakeblackshear/frigate#9991] opened 2024-02-23 09:42 UTC
**Describe what you are trying to accomplish and why in non technical terms**
Sometimes regardless of settings i'll find a large number of recordings of stationary vehicles overnight I can't deal with through zones / boxes or another long run of recordings that I'd like to remove to free up storage. Individually deleting these clip by clip is time consuming; a tickbox / mass deletion feature to select events and delete in one hit would be useful. 

**Describe the solution you'd like**
A tickbox on each event and a delete button, or a screen similar to the "snapshots" page in the HA integration lovelace card on which large numbers of clips can be selected and removed en masse.

**Comment by NickM-27** [comment] 2024-02-23 13:26
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2223

**Closed by NickM-27** 2024-02-23 13:26 UTC
Labels: duplicate, enhancement
