### ISSUE TITLE
Link to live view when clicking on a particular camera's part of the birdseye view.

### ISSUE THREAD

**Issue by ksheyman** [blakeblackshear/frigate#7373] opened 2023-08-03 06:05 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to click on a camera view in birdseye and have it link to the live view. 

**Describe the solution you'd like**
I recently implemented go2rtc using my substreams for detection, while using the main stream for recordings. When using Birdseye, I'd like to be able to just click on the the portion of the Birdseye view where my camera is displayed and be linked to a full-screen view of the full-quality live stream. I'd also like to be able to dis-engage the live view with another click and return to Birdseye.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by NickM-27** [comment] 2023-08-03 12:29
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1735

**Closed by NickM-27** 2023-08-03 12:29 UTC
Labels: duplicate, enhancement
