### ISSUE TITLE
User Experience Improvements for Frigate+ Model Training

### ISSUE THREAD

**Issue by theyapps** [blakeblackshear/frigate#10222] opened 2024-03-04 01:53 UTC
**Describe what you are trying to accomplish and why in non technical terms**
When using the training interface on frigate+ data entry can be very monatonous for many frames with objects that remain stationary across many frames.

**Describe the solution you'd like**
I would like to see the previous labeled objects remain when moving to a new submitted frame so that the user can verify if they are the same as often objects remain stationary for many frames.

**Describe alternatives you've considered**
Additionally, I think it would be beneficial to have an option to run frames through object detection and allow a suggestion to be shown and verified rather than labelling all objects being manually entered everytime.

**Additional context**
N/A

**Comment by NickM-27** [comment] 2024-03-04 01:54
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/8229

**Closed by NickM-27** 2024-03-04 01:54 UTC
Labels: duplicate, enhancement

**Comment by theyapps** [comment] 2024-03-04 02:15
I see that duplicate of the alternative considered solution. Appreciate the consideration.
