### ISSUE TITLE
[Config Support]: Intel HWACCEL

### ISSUE THREAD

**Issue by madasus** [blakeblackshear/frigate#4365] opened 2022-11-10 20:40 UTC
### Describe the problem you are having

I read a few other threads about the Adler Lake GPU chipset

https://github.com/blakeblackshear/frigate/issues/3170

But running the latest version i'm still struggling.

Running Intel Gen 12 (Adler Lake) Ubuntu 22.04.  Using a coral as well which works perfectly.

Frigate in docker - latest stable release.

Any ideas what is going on?

---docker compose script---
version: "3"
services:
  frigate:
    image: blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /volume1/docker/frigate/config:/config
      - /volume1/docker/frigate/db:/db
      - /volume1/docker-temp/frigate/media:/media/frigate
      - /etc/localtime:/etc/localtime:ro
      - /dev/bus/usb:/dev/bus/usb
    environment:
     - PUID=0
     - PGID=0
     - TZ=America/New York
     - FRIGATE_RTSP_PASSWORD="XXX"
    restart: unless-stopped

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: XXX
  user: XXX
  password: XXX

ffmpeg:
  hwaccel_args: -c:v h264_qsv

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
[2022-11-10 20:36:41] watchdog.catgenie2             ERROR   : Ffmpeg process crashed unexpectedly for catgenie2.
[2022-11-10 20:36:41] watchdog.catgenie2             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [AVHWDeviceContext @ 0x557711aad1c0] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [AVHWDeviceContext @ 0x557711aad1c0] Failed to initialise VAAPI connection: 1 (operation failed).
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [h264_qsv @ 0x557711b50300] Failed to create a VAAPI device.
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [h264_qsv @ 0x557711b50300] Error initializing an MFX session
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [h264_qsv @ 0x557711b50300] Error decoding header
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : Error while decoding stream #0:0: Input/output error
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [segment @ 0x557711a1dc80] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [flv @ 0x557711a1fcc0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [h264_qsv @ 0x557711b50300] video_get_buffer: image parameters invalid
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [h264_qsv @ 0x557711b50300] get_buffer() failed
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : Error while decoding stream #0:0: Invalid argument
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : Finishing stream 2:0 without any data written to it.
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711b5e2c0] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711b6b280] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711b78240] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711bf4000] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711c353c0] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711c76780] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711cb7b40] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711cf8f00] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711d3a2c0] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711d7b680] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711dbca40] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711dfde00] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [swscaler @ 0x557711b50740] [swscaler @ 0x557711e3f1c0] deprecated pixel format used, make sure you did set range correctly
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [flv @ 0x557711a1fcc0] Failed to update header with correct duration.
[2022-11-10 20:36:41] ffmpeg.catgenie2.detect        ERROR   : [flv @ 0x557711a1fcc0] Failed to update header with correct filesize.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

root@host1:/volume1/docker/build# vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.3.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc

**Comment by NickM-27** [comment] 2022-11-10 20:49
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3941, recommend reading there

**Closed by NickM-27** 2022-11-10 20:49 UTC
Labels: support, triage
