### ISSUE TITLE
Small QOL change for Birdseye

### ISSUE THREAD

**Issue by rourke750** [blakeblackshear/frigate#11016] opened 2024-04-18 00:03 UTC
I want to be able to have a full screen url for birdseye so that I can cast this url to my tv/casting device.  Currently if I want to cast it I have my tabs on the left and control panel on the right for ptz cameras.  

If I was able to have a dedicated url that only showed the birdseye and nothing else that would be very useful for casting/devices that do not have input and wouldnt need the menu options.

**Comment by NickM-27** [comment] 2024-04-18 00:10
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1891

Also if you enable birdseye restreaming then it already works like this.

**Closed** 2024-04-18 00:10 UTC
Labels: duplicate, enhancement

**Comment by rourke750** [comment] 2024-04-18 04:19
I dont think you can just cast rtsp to a chromecast.  Tried doing the restream and got it working in vlc but cant get it to cast.

**Comment by rourke750** [comment] 2024-04-18 14:33
Is this already documented in the frigate docs somewhere?  Been looking there and at the go2rtc docs and not really finding what I need.  Also does this involve additional ports and configurations?  Casting the main page works perfectly just dont want the menus.

**Comment by NickM-27** [comment] 2024-04-18 14:34
You'd need port 1984 open and that's where you'd get the link for HLS stream
