### ISSUE TITLE
Camera enable/disable

### ISSUE THREAD

**Issue by tomhub** [blakeblackshear/frigate#7126] opened 2023-07-11 13:11 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have camera that are not switched on all the time. I have internal cameras that I only switch on when going away for longer periods of time. So, for these cameras, I would like those cameras to be checked if they are online every 30 minutes or other custom time. Ex. when connection is lost or frigate is started, try to connect to it: if failed, wait 10s and try again; if failed, wait 10s try again; if failed again wait 30 min and try again (and if failed repeat every 30 min interval).

After successful connection and the loss of connection, repeat reconnect sequence again: 10s 10s 30min. 

**Describe the solution you'd like**
When camera cannot be found online (eg. ping/connection drop), after second time, check if it is online in 30 minutes. This option should be setup in within cameras, ex. 
```
go2rtc:
  streams:
    temp_cam:
      - rtsp://...
      -  "ffmpeg:..
      - reconnect: 10s 10s 30min
```  

**Describe alternatives you've considered**
Alternatively, not do anything, and see log files being grown constantly with errors of failed connections

**Additional context**
Nice to have an option to check restart reconnection to cameras sequence once Alarmo is armed in home assistant.

This would lower resource of starting ffmpeg too often, and have a cleaner log.

**Comment by NickM-27** [comment] 2023-07-11 13:15
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1911

**Closed by NickM-27** 2023-07-11 13:15 UTC
Labels: duplicate, enhancement
