### ISSUE TITLE
Add role specifically for continuous background recording

### ISSUE THREAD

**Issue by blacktirion** [blakeblackshear/frigate#5819] opened 2023-03-23 20:33 UTC
**Describe what you are trying to accomplish and why in non technical terms**
A good portion of people who recommend BlueIris (even to this day) recommend recording the sub stream continuously, while using the higher resolution for events. This is mostly possible with the current setup, but lacks some integration with the timeline. The current way to do this is to set the continuous record to happen on an additional camera entry in the config.

**Describe the solution you'd like**
Create a specific continuous record role that allows the user to choose a different stream than the regular record role, which is utilized for the events.

**Describe alternatives you've considered**
I have set up a specific entity/entry in the config that saves the lower res restream to disk for 30 days. This is a camera object. The problem with this approach is that the timeline view of recordings is not joined, so a user can not easily correlate events between 24/7 recording and the events.  In the case where a user has specific events only taking snapshots, the user may not have full-res video to fall back on. Or in the case where a detection didn't go when it was supposed to.

**Additional context**
I am doing restreaming via go2rtc. This works quite well when splitting out the main/sub streams multiple times for various recording/detection activities.

**Comment by NickM-27** [comment] 2023-03-23 20:35
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/2082

feel free to leave a comment with additional information and support it with a 👍 on the main issue

**Closed by NickM-27** 2023-03-23 20:35 UTC
Labels: duplicate, enhancement
