### ISSUE TITLE
Add Events Filter for Time Range - TimePicker

### ISSUE THREAD

**Issue by Normanras** [blakeblackshear/frigate#4001] opened 2022-10-02 21:46 UTC
**Describe what you are trying to accomplish and why in non technical terms**
For a few events, I often just want to see images/clips captured during certain time ranges. The two obvious examples are when someone is supposed to be visiting my home when I'm not there, or to view all night time activity, such as when animals are visiting my camera. 

**Describe the solution you'd like**
Under the events filters, I would love to see either:

1. An additional filter called "Time Picker" 
2. Or some pre-set time ranges within date picker (morning, afternoon, night, etc)

**Describe alternatives you've considered**
None, really.

**Comment by NickM-27** [comment] 2022-10-02 21:57
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3140 which has a draft implementation https://github.com/blakeblackshear/frigate/pull/3302

**Closed by NickM-27** 2022-10-02 21:57 UTC
Labels: duplicate, enhancement
