### ISSUE TITLE
Enabled / disabled mask for camera

### ISSUE THREAD

**Issue by ramirez22-fr** [blakeblackshear/frigate#13289] opened 2024-08-23 12:27 UTC
**Describe what you are trying to accomplish and why in non technical terms**
Using PTZ cam with mask isn't easy : at each change, mask don't fit with the new scene and some move are detected and another not. 
I would enable or disable mask (or group of masks) for each PTZ preset position.

**Describe the solution you'd like**
"Little" change in the yaml/mqtt
- add name to each mask (or a group of masks) and an 'enabled' status
- add the ability to modify the status of each mask (true or false)

**Additional context**
With this mod, it will be possible to :
- activate a mask (or group) for a preset
- disable motion detection before change position to another preset
- disable mask of the old preset, enable mask of the new position and enable motion detection
No hard CPU/TPU sollicitation during move and mask optimisation for each PTZ preset

I have no idea about how much this modification will be difficult to do, but I'm sure that every PTZ camera owner will be interested

(PS : sorry for my bad english, not my natal language ...)

**Comment by NickM-27** [comment] 2024-08-23 12:36
I am going to close this as a duplicate of https://github.com/blakeblackshear/frigate/issues/3621

**Closed by NickM-27** 2024-08-23 12:36 UTC
Labels: duplicate, enhancement
