### ISSUE TITLE
Add a way to review video and check debug information

### ISSUE THREAD

**Issue by antonellopasella** [blakeblackshear/frigate#15232] opened 2024-11-28 07:48 UTC
I want to be able to play old videos and see debug information (based on actual configuration) in order to review/check new settings against older videos.

**Comment by hawkeye217** [comment] 2024-11-28 12:41
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1914

**Closed** 2024-11-28 12:41 UTC
Labels: enhancement
