### ISSUE TITLE
Request: run encoding *after* motion detection (e.g. convert video to h264)

### ISSUE THREAD

**Issue by roger-** [blakeblackshear/frigate#4415] opened 2022-11-16 18:50 UTC
I'm running Frigate with several MJPEG cameras and it's setup to transcode them to H264, which seems rather wasteful since it's always happening.

How about if clips were saved in whatever format (e.g. MJPEG) and we could then batch convert them to h264 after motion was successfully detected?

There could be an additional  `post_record` option for configuring the relevant `input/output_args` for ffmpeg, or a more general option to run a command (with special variables representing the input and output file names).

**Comment by NickM-27** [comment] 2022-11-16 19:06
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/2243

**Closed** 2022-11-19 15:51 UTC
Labels: duplicate, enhancement
