### ISSUE TITLE
Error in log attempting to export footage from Safari

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#6782] opened 2023-06-12 22:50 UTC
### Describe the problem you are having

It's 6/12/23 at 4:43PM local time. I attempted to export from a camera at 6/12/23 from 4:41PM to 4:42PM.

### Version

0.13.0-FF90DB3

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 90
    mode: motion
  events:
    pre_capture: 2
    post_capture: 2

<snip>
```

### Relevant log output

```shell
2023-06-12 22:43:45.295162319  [2023-06-12 22:43:45] frigate.http                   ERROR   : Exception on /export/driveway/start/NaN/end/NaN [POST]
2023-06-12 22:43:45.295169189  Traceback (most recent call last):
2023-06-12 22:43:45.295171287    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
2023-06-12 22:43:45.295172944      response = self.full_dispatch_request()
2023-06-12 22:43:45.295175094    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
2023-06-12 22:43:45.295176621      rv = self.handle_user_exception(e)
2023-06-12 22:43:45.295178493    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
2023-06-12 22:43:45.295179990      rv = self.dispatch_request()
2023-06-12 22:43:45.295181882    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
2023-06-12 22:43:45.295183672      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-06-12 22:43:45.295185642    File "/opt/frigate/frigate/http.py", line 1514, in export_recording
2023-06-12 22:43:45.295187243      int(start_time),
2023-06-12 22:43:45.295188821  ValueError: invalid literal for int() with base 10: 'NaN'
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

I checked, and I don't have any recorded segments for this timespan. So I guess I'm just expecting it to fail more gracefully with "no recorded segments found between X and Y" instead of the UI reporting "Successfully started export. View the file in the /exports folder.", but the network inspector showing the POST to api/export failed with a 500, and an error parsing the int in the logs.

**Comment by ccutrer** [comment] 2023-06-12 22:51
In case this is actually a front-end problem with the time picker, I'm using Safari 16.5 on macOS.

**Comment by NickM-27** [comment] 2023-06-12 22:52
Currently this isn't going to be supported. It is quite difficult architecturally to do that since we'd essentially have to wait for the clip to finish which would blow past any timeout. The UI is very basic right now and that's on purpose, a future version will be more robust.

**Comment by ccutrer** [comment] 2023-06-12 22:54
Hmm, I'm not sure this actually has to do with recent or missing recording segments. I'm getting the exact same problem trying to export from 4:10pm to 4:12pm, which I _know_ has clips. So this is feeling more like a frontend problem. I can't export _anything_.

**Comment by ccutrer** [comment] 2023-06-12 22:56
Yes, it _does_ work in Google Chrome with the same timestamps. So definitely a frontend issue in Safari.

**Comment by NickM-27** [comment] 2023-06-12 22:57
Interesting, perhaps that is what @skrashevich was referring to with different browser compatibility in the PR. I will see what the issue is with Safari

**Comment by ccutrer** [comment] 2023-06-12 23:06
Nothing fancy. I am going through a reverse proxy, but I don't see how that would affect it. I'm in UTC-6 (both my Frigate server, and my browser), so I even if something is getting interpreted as UTC, I would think it would just show me something old? Other than that, I went to /exports, chose a camera more likely to have recordings, chose Realtime, and typed in some dates and times, then clicked Submit.

<img width="1119" alt="Screenshot 2023-06-12 at 5 01 58 PM" src="https://github.com/blakeblackshear/frigate/assets/191320/c2471573-1cc6-4edb-a91a-3ea67663dbb4">

The browser console logged two errors:

`Failed to load resource: the server responded with a status of 500 ()`
`Unhandled Promise Rejection: AxiosError: Request failed with status code 500`

**Comment by NickM-27** [comment] 2023-06-12 23:15
ah I see the issue, you have not confirmed the dates just the times. Not sure why the validation is not catching that

**Comment by ccutrer** [comment] 2023-06-12 23:17
Ah, I see, yes. Clicking into them and (re-selecting) the dates with the calendar gets rid of the error. Previously I had directly typed them in.

**Comment by NickM-27** [comment] 2023-06-14 12:34
Fixed in https://github.com/blakeblackshear/frigate/pull/6794

**Closed by NickM-27** 2023-06-14 12:34 UTC
Labels: support, triage

**Comment by ccutrer** [comment] 2023-06-14 16:41
Can confirm this is now working as expected for me.
