### ISSUE TITLE
If Coral device errors/not found in config, fall back to CPU detector if specified in config

### ISSUE THREAD

**Issue by goldserve** [blakeblackshear/frigate#8792] opened 2023-11-29 18:21 UTC
**Describe what you are trying to accomplish and why in non technical terms**
Everything was running great for weeks and then the Coral device errored on the USB bus and needed a full system reset. If I used CPU detector and restarted the docker, everything is OK. At least I won't have a time when the NVR stops/

**Describe the solution you'd like**
Just fall back to CPU detector without taking down the whole security camera application

**Describe alternatives you've considered**

**Additional context**

**Comment by NickM-27** [comment] 2023-11-29 18:22
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/2904

**Closed by NickM-27** 2023-11-29 18:22 UTC
Labels: duplicate, enhancement
