### ISSUE TITLE
Toggle Specific Objects On or Off

### ISSUE THREAD

**Issue by codeinstitution** [blakeblackshear/frigate#13993] opened 2024-09-26 19:59 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to toggle detection for certain objects on/off without editing the frigate.yaml. Ideally via API/MQTT/Home Assistant. For example, when I have company over, I don't want to record if it detects people on my porch but still want to record if a new car comes in or pets etc. Then when company leaves, go back to detecting people again. Right now, I have to manually edit the yaml which gets annoying so I just turn off detection all together.

**Describe the solution you'd like**
API/MQTT/Home Assistant ability to toggle detect

**Comment by NickM-27** [comment] 2024-09-26 20:03
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2329

**Closed by NickM-27** 2024-09-26 20:03 UTC
Labels: duplicate, enhancement
