### ISSUE TITLE
Motion tuning / debugging with stored footage

### ISSUE THREAD

**Issue by vertex-github** [blakeblackshear/frigate#15151] opened 2024-11-23 16:31 UTC
It would be really helpful if I could replay stored footage through the debug and motion detection windows.  Those are great tools for live footage, but thats not useful after the fact if Im trying to tune the settings for missed object/motion detection.  

If I could have a timeline slider for the camera I'm tuning/debugging, and then see what Frigate thinks of my new settings (perhaps treat it as a temporary camera/config for the purposes of tuning / using hardware accel and TPUs) it would be great.

**Comment by hawkeye217** [comment] 2024-11-23 17:34
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1914

**Closed by hawkeye217** 2024-11-23 17:34 UTC
Labels: enhancement
