### ISSUE TITLE
Add support to enable / disabling certain users (except admin)

### ISSUE THREAD

**Issue by wauswaus** [blakeblackshear/frigate#14622] opened 2024-10-27 12:28 UTC
**Describe what you are trying to accomplish and why in non technical terms**
During holidays I would like to give access to friends to keep an eye on our place. However, when not on holiday I would like to be able to disable that user account so they can't spy on us :)
For us this scenario happens quite regularly.

**Describe the solution you'd like**
In the user setting screen, add a tick box so a user can be disabled and thus not be able to log in. The admin account should not be able to be disabled.

**Describe alternatives you've considered**
An alternative would be to constantly make a new user and delete it again. However, towards my friends that is not very user friendly as I then also have to share a new password. As said, this scenario happens quite often so it is quite annoying to my friends.

**Comment by hawkeye217** [comment] 2024-10-27 12:36
Roles/groups/permissions already has a pinned feature request and is planned for a future version. This is a duplicate of https://github.com/blakeblackshear/frigate/issues/6614

**Closed by hawkeye217** 2024-10-27 12:36 UTC
Labels: enhancement
