### ISSUE TITLE
[Support]: beta4 tensorrt crash on startup

### ISSUE THREAD

**Issue by vajonam** [blakeblackshear/frigate#8464] opened 2023-11-05 00:57 UTC
### Describe the problem you are having

not able to startup cleanly and stay up see this in the logs

```
frigate           | 2023-11-04 20:52:35.082847546  Process detector:p106:
frigate           | 2023-11-04 20:52:35.084154322  Traceback (most recent call last):
frigate           | 2023-11-04 20:52:35.084234318    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate           | 2023-11-04 20:52:35.084237449      self.run()
frigate           | 2023-11-04 20:52:35.084273102    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate           | 2023-11-04 20:52:35.084276010      self._target(*self._args, **self._kwargs)
frigate           | 2023-11-04 20:52:35.084310048    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
frigate           | 2023-11-04 20:52:35.084312930      detections = object_detector.detect_raw(input_frame)
frigate           | 2023-11-04 20:52:35.084354425    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
frigate           | 2023-11-04 20:52:35.084357483      return self.detect_api.detect_raw(tensor_input=tensor_input)
frigate           | 2023-11-04 20:52:35.084391571    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 307, in detect_raw
frigate           | 2023-11-04 20:52:35.084394572      raw_detections[:, 4] = raw_detections[:, 4] * raw_detections[:, 6]
frigate           | 2023-11-04 20:52:35.084439946  TypeError: list indices must be integers or slices, not tuple
```

previous beta 3 was working

### Version

0.13-beta4

### Frigate config file

```yaml
No changes since working dev-159fb51-tensorrt
```

### Relevant log output

```shell
frigate           | 2023-11-04 20:52:35.082847546  Process detector:p106:
frigate           | 2023-11-04 20:52:35.084154322  Traceback (most recent call last):
frigate           | 2023-11-04 20:52:35.084234318    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate           | 2023-11-04 20:52:35.084237449      self.run()
frigate           | 2023-11-04 20:52:35.084273102    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate           | 2023-11-04 20:52:35.084276010      self._target(*self._args, **self._kwargs)
frigate           | 2023-11-04 20:52:35.084310048    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
frigate           | 2023-11-04 20:52:35.084312930      detections = object_detector.detect_raw(input_frame)
frigate           | 2023-11-04 20:52:35.084354425    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
frigate           | 2023-11-04 20:52:35.084357483      return self.detect_api.detect_raw(tensor_input=tensor_input)
frigate           | 2023-11-04 20:52:35.084391571    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 307, in detect_raw
frigate           | 2023-11-04 20:52:35.084394572      raw_detections[:, 4] = raw_detections[:, 4] * raw_detections[:, 6]
frigate           | 2023-11-04 20:52:35.084439946  TypeError: list indices must be integers or slices, not tuple
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest

**Comment by NickM-27** [comment] 2023-11-05 00:58
Duplicate of https://github.com/blakeblackshear/frigate/issues/8460

**Closed by NickM-27** 2023-11-05 00:58 UTC
Labels: support, triage
