### ISSUE TITLE
Allow recording multiple streams per camera

### ISSUE THREAD

**Issue by d3relict** [blakeblackshear/frigate#11458] opened 2024-05-20 21:25 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to record both high and low resolution streams so that I can upload the low resolution real time to a cloud backup solution in case my home is invaded and my server is stolen. Uploading the low resolution should still be enough for investigation and would not stress the internet connection that much.

**Describe the solution you'd like**
Separately stored, with individual retention for each stream version, so the user can mirror the recordings folder to a remote storage, and rely on Frigate to remove old segments.

**Describe alternatives you've considered**
I have no alternative idea, apart from duplicating cameras, which sounds suboptimal.

**Additional context**
n/a

**Comment by NickM-27** [comment] 2024-05-20 21:27
the next version of frigate supports previews which are a low fps low resolution "summary video" and that may be enough for this issue. In any case this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2652

**Closed by NickM-27** 2024-05-20 21:27 UTC
Labels: duplicate, enhancement
