### ISSUE TITLE
Fall back to CPU detection when TPU not found

### ISSUE THREAD

**Issue by clearwave1** [blakeblackshear/frigate#8768] opened 2023-11-27 22:43 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I'm running Proxmox with Frigate in Docker in an LXC container and the PCI Coral TPU works fine but will stop responding about once per week and I cannot find a way to get it working without restarting the physical host. When this happens Frigate goes into a restart loop and nothing is captured or detected until I reboot the server. When this happens I cannot even view the cameras as Frigate is restarting constantly.

**Describe the solution you'd like**
It would be helpful if Frigate could fall back to CPU detection when it cannot find the TPU. This would allow Frigate to continue working properly even if it cannot use the TPU.

**Describe alternatives you've considered**
Troubleshooting of the Coral TPU issue but no stable solutions so far.

**Additional context**

**Comment by NickM-27** [comment] 2023-11-27 22:46
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2904

**Closed by NickM-27** 2023-11-27 22:46 UTC
Labels: duplicate, enhancement
