### ISSUE TITLE
[Support]: [UI] Copy button in mask editor does not work.

### ISSUE THREAD

**Issue by flowchartsman** [blakeblackshear/frigate#2594] opened 2022-01-06 05:48 UTC
### Describe the problem you are having

When clicking the `COPY` button in the Zone and Mask editor, nothing is copied to the clipboard.

Chrome version: 96.0.4664.110 (Official Build) (arm64)

Additionally, the following error appears in the development tools on click:

![image](https://user-images.githubusercontent.com/926884/148334885-31a1bd34-ad79-471e-b727-fea61006dee1.png)

### Version

0.9.4-26AE608

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
(see above)
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment] 2022-01-14 23:52
@blakeblackshear I still experience this on 0.10.0 so I was going to try to fix it but when built locally I am no longer able to reproduce the issue. Perhaps it was fixed in a later commit 🤔

**Comment by ve6rah** [comment] 2022-02-02 16:34
tried it today and it still won't copy for me.

Of course when I manually copy and paste it to my config file it's ignored anyway, but that's a separate problem.

**Comment by NickM-27** [comment] 2022-02-02 16:36
@ve6rah did you build manually from the branch? Because that's what I meant

**Comment by NickM-27** [comment] 2024-04-10 20:02
the UI is currently being rewritten for the next version of frigate (0.14), this is no longer relevant

**Closed by NickM-27** 2024-04-10 20:02 UTC
Labels: support, pinned
