### ISSUE TITLE
[Support]: Frigate NVR Proxy in HA does not show Frigate anymore after upgrade to 0.11.0-b2

### ISSUE THREAD

**Issue by Calimerorulez** [blakeblackshear/frigate#3314] opened 2022-06-08 08:03 UTC
### Describe the problem you are having

I've just upgraded to Frigate 0.11.0-b2, and now the Home Assistant Frigate NVR Proxy does not show anything anymore. I've tried to reinstall the add-on, but that does not resolve the issue.

### Version

0.11.0-D2C3CDC

### Frigate config file

```yaml
Not relevant?
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Frigate NVR Proxy
 Proxy addon for Frigate
-----------------------------------------------------------
 Add-on version: 1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.1  (amd64 / qemux86-64)
 Home Assistant Core: 2022.6.4
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:57:32] INFO: Starting NGinx...
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Unifi

### Any other information that may be helpful

My Frigate install is on a separate machine; calling the Frigate URL directly does show the interface on port 5000. The HA add-on shows an empty page.

**Comment by NickM-27** [comment] 2022-06-08 11:17
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3230

**Comment by Calimerorulez** [comment] 2022-06-08 13:51
@NickM-27 
Thank you, sorry for overlooking. Shall I close this issue then?

**Closed** 2022-06-08 15:43 UTC
Labels: support, triage
