### ISSUE TITLE
language

### ISSUE THREAD

**Issue by Kotyabus** [blakeblackshear/frigate#12739] opened 2024-08-03 11:55 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NickM-27** [comment] 2024-08-03 12:01
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/925

**Closed** 2024-08-03 12:01 UTC
Labels: duplicate, enhancement
