### ISSUE TITLE
Clicking on a camera in birdseye, Opens that camera's page

### ISSUE THREAD

**Issue by spacebares** [blakeblackshear/frigate#4229] opened 2022-11-01 19:31 UTC
Clicking on a camera in birdseye, Opens that camera's page. So you can see the camera live feed & its events. Quick little shortcut.

**Comment by NickM-27** [comment] 2022-11-01 19:32
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1735

**Closed by NickM-27** 2022-11-01 19:32 UTC
Labels: duplicate, enhancement
