### ISSUE TITLE
Recognize household members

### ISSUE THREAD

**Issue by nick2525** [blakeblackshear/frigate#5189] opened 2023-01-22 11:42 UTC
I have to recognize household members easily 1) uploaded their photo 2) click on the video that they are here they are not here 3) and that's it, I have to get the MQTT event for this
This is how the Netatmo camera works, other actions are not suitable for inexperienced users

**Comment by NickM-27** [comment] 2023-01-22 13:23
We recommend doubletake for this. https://github.com/jakowenko/double-take. What you're describing is exactly how doubletake works and it integrates with frigate

This also a duplicate of https://github.com/blakeblackshear/frigate/issues/260

**Closed** 2023-01-22 13:23 UTC
Labels: duplicate, enhancement
