### ISSUE TITLE
Multiple Camera Playback, or Playback of all recordings with the same Zone name spanning multiple cameras

### ISSUE THREAD

**Issue by Deckoz2302** [blakeblackshear/frigate#5122] opened 2023-01-16 20:50 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to select all cameras with zone driveway, street, sidewalk etc(named zone in the cameras configuration). And play all cameras with that zone configured at the same time instead of going to events, filtering by street, and having to click each event(the same event from a different camera) and watching individually.

**Describe the solution you'd like**
A page similar to birdseye, except for all cameras with 'zone_name' matching, to playback at the same time. 

**Describe alternatives you've considered**
On the recordings page, if 24/7 recording is in place, select the camera feeds you wish to display, and have a single time slider bar to scroll through the feeds of all cameras selected for the view.

**Additional context**
Frigate is great at object detection, and it's 24/7 recording is also very good. So much so that it negates running other software such as blue iris. But it is missing one key feature - playback of multiple feeds at the same time.  Frigate already handles live viewing of multiple feeds. This is a feature that would really make frigate a very well rounded NVR and all in one solution for most users.

**Comment by NickM-27** [comment] 2023-01-16 20:52
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1695

**Comment by NickM-27** [comment] 2023-01-16 20:52
Feel free to leave any additional details on that page and leave a 👍 on the header post

**Closed by NickM-27** 2023-01-16 20:52 UTC
Labels: enhancement

**Comment by Deckoz2302** [comment] 2023-01-16 21:03
Thanks @NickM-27 I looked through issues first, must have missed it in the 210 open. My apologies.
