### ISSUE TITLE
Specify different detectors or models  per camera

### ISSUE THREAD

**Issue by SpangleLabs** [blakeblackshear/frigate#9917] opened 2024-02-19 13:11 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to specify different models or detectors to be used by different cameras so that I can use a model optimised for different use-cases on different cameras. Such as using a normal model for my CCTV cameras, while using one trained on bird detection/recognition or something on a bird box camera

**Describe the solution you'd like**
Being able to specify which model a camera should use in the camera config would be the basic solution.
I don't think this would mean needing to specify multiple models at the base of the config, as that would be confusing perhaps, but being able to override the model configured at the base, for a given camera, would be good.

Being able to specify the detectors would also be very helpful, such that I can define a custom detector which exports all the model input and output somewhere, such that I could work on building and training such a model. However, that might be surplus? I'm not sure whether that would be functionality wanted upstream at all, or just something I do locally.
At the moment, it seems detectors initialise with a reference to the model, so I'm not sure whether specifying detectors for a camera might help there too.

**Describe alternatives you've considered**
I considered separate detectors, as mentioned, but then realised that's not possible either.
Another option would be to run a second Frigate instance, but that seems like overkill.

I pondered making a model that output into a different segment of the label map than other cameras use, and then the bird box camera can listen to, for example, `banana`, `wine glass`, `orange`, while the cctv cameras listen to `person`, `car`, `bird`. AS many of the base label map is mostly unused in a CCTV context anyway. But that would be confusing, and ideally would want to be able to specify `model.labelmap` overrides by camera anyway, so that the names made sense again.

**Additional context**
This arose in a discussion about the same, more context may be there: https://github.com/blakeblackshear/frigate/discussions/9894

**Comment by NickM-27** [comment] 2024-02-19 13:19
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/1301

**Closed by NickM-27** 2024-02-19 13:19 UTC
Labels: duplicate, enhancement

**Comment by SpangleLabs** [comment] 2024-02-19 13:52
Ah, darnit, apologies
