### ISSUE TITLE
Toggle a Camera in the same way you can Toggle Detect/Recordings/Snapshots

### ISSUE THREAD

**Issue by philosowaffle** [blakeblackshear/frigate#7841] opened 2023-09-16 18:24 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I have several cameras inside of my home. While I am home, for privacy and security reasons, I prefer to have these cameras completely turned off. I achieve this by cutting power via a smart plug.  This is all automated using presence detection and HomeAssistant.   However, whenever a camera goes offline, it has the side effect of causing the ffmeg process to repeatedly crash and restart.  Across the 3 cameras I have, this yields _hundreds_ of ERROR logs per minute.  Below is a sample of these logs for one of my cameras, note that I have Detect, Snapshot, and Recordings disabled for the offline camera.

```
 [2023-09-16 12:04:58] watchdog.living_room_01        ERROR   : Ffmpeg process crashed unexpectedly for living_room_01.
 [2023-09-16 12:04:58] watchdog.living_room_01        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
 [2023-09-16 12:04:58] ffmpeg.living_room_01.detect   ERROR   : [tcp @ 0x563e7a2fbdc0] Connection to tcp://192.168.1.210:1935?tcp_nodelay=0 failed: No route to host
 [2023-09-16 12:04:58] ffmpeg.living_room_01.detect   ERROR   : [rtmp @ 0x563e7a2fb380] Cannot open connection tcp://192.168.1.210:1935?tcp_nodelay=0
[2023-09-16 12:04:58] ffmpeg.living_room_01.detect   ERROR   : rtmp://192.168.1.210/bcs/channel0_main.bcs?channel=0&stream=0&user=*&password=* No route to host
```

**Describe the solution you'd like**
I would like to not have these error messages flooding the logs, and ideally not have the ffmpeg process constantly crashing/rebooting.  Two options I can think of handling this differently:

1. Adjusting the logic in frigate to handle offline camera's more gracefully, and with fewer error messages
2. Provide a global Toggle for the Camera itself. This Toggle could be used to stop the ffmpeg process and release any other resources for that camera until it is re-enabled.

**Describe alternatives you've considered**
Two ideas mentioned above, open to other options as well.  I could turn off logging, but I then I run the risk of missing _real_ errors that could be important.

**Additional context**

![firefox_2023-09-16_13-23-55](https://github.com/blakeblackshear/frigate/assets/7275041/8297d168-7d1e-407b-8538-9792948cef99)
![firefox_2023-09-16_13-23-42](https://github.com/blakeblackshear/frigate/assets/7275041/3ebbc468-0f23-4108-9f90-dfaf39e6afef)

**Comment by NickM-27** [comment] 2023-09-16 19:03
This is a duplicate of #1911

**Closed** 2023-09-16 19:04 UTC
Labels: duplicate, enhancement
