### ISSUE TITLE
Frigate+ submission re-classification of all objects in frame

### ISSUE THREAD

**Issue by mjdyson** [blakeblackshear/frigate#11529] opened 2024-05-26 10:18 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to reduce the time spent labelling objects within a frigate+ submission so that I can spend more time submitting more photos.

**Describe the solution you'd like**
The current workflow only identifies a single item in the image - I presume this is because it takes the bounding box from the original motion tile (snapshot?) and then overlays it on top of the bigger video frame that it came from. Within this image, there may be multiple objects that are untagged that needs to be bounded and labelled. This starts to get a bit tedious for objects that might be fairly static (cars, plants etc). 

It would be great if there was a pipeline that could send a bit more through the local classifier. Perhaps, the whole frame looking for new items, or more pragmatically, an auto-labelling of a new bounding box.

**Comment by NickM-27** [comment] 2024-05-26 11:26
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/8229

**Closed** 2024-05-26 11:27 UTC
Labels: duplicate, enhancement
