### ISSUE TITLE
[Detector Support]: Python exception - TypeError: list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by ramunasd** [blakeblackshear/frigate#8491] opened 2023-11-06 10:13 UTC
### Describe the problem you are having

TernsorRT fails to start on Jetson Nano jp4 using docker. Older beta `dev-16dc9f4-tensorrt-jp4` was working fine.

### Version

dev-89dd114-tensorrt-jp4

### Frigate config file

```yaml
mqtt:
  enabled: false

go2rtc:
  streams:
    sub_stream:
    - rtsp://192.168.1......

cameras:
  camera:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
      - path: rtsp://127.0.0.1:8554/sub_stream
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://192.168.1....
        roles:
        - record
    live:
      stream_name: sub_stream
    motion:
      threshold: 50
      delta_alpha: 0.05
      frame_alpha: 0.08


ffmpeg:
  hwaccel_args: preset-jetson-h264

live:
  height: 720
  quality: 10

motion:
  threshold: 40
  delta_alpha: 0.15
  frame_alpha: 0.15

detectors:
  tensorrt:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

detect:
  width: 1280
  height: 720
  fps: 3
  enabled: true

objects:
  track:
  - person
  - bird
  - cat
  - dog

snapshots:
  enabled: true
  bounding_box: true
  clean_copy: true
  quality: 80

record:
  enabled: true
  sync_on_startup: true
  retain:
    days: 3
    mode: motion
  events:
    pre_capture: 1
    post_capture: 5
    retain:
      default: 14
      mode: motion
      objects:
        person: 30

birdseye:
  enabled: false

ui:
  live_mode: mse
  use_experimental: false

telemetry:
  version_check: false
```

### docker-compose file or Docker CLI command

```yaml
docker run \
  --detach \
  --restart unless-stopped \
  --name frigate \
  --privileged \
  --runtime nvidia \
  --gpus all \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --shm-size=64m \
  -v $PWD/media:/media/frigate \
  -v $PWD/config:/config \
  -v /etc/localtime:/etc/localtime:ro \
  -p 5000:5000 \
  -p 8554:8554 \
  -p 8555:8555/tcp \
  -p 8555:8555/udp \
  ghcr.io/blakeblackshear/frigate:dev-89dd114-tensorrt-jp4
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service trt-model-prepare: starting
s6-rc: info: service log-prepare: starting
No models to convert.
s6-rc: info: service trt-model-prepare successfully started
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-11-06 11:59:11.257681362  [INFO] Preparing Frigate...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-11-06 11:59:11.266010756  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-11-06 11:59:11.312927183  [INFO] Preparing go2rtc config...
2023-11-06 11:59:11.445761397  [INFO] Starting Frigate...
2023-11-06 11:59:11.931362312  2023/11/06 11:59:11 [error] 152#152: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /ws HTTP/1.1", upstream: "http://127.0.0.1:5002/", host: "cam.lan"
2023-11-06 11:59:11.932336857  172.17.0.1 - - [06/Nov/2023:11:59:11 +0200] "GET /ws HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0" "192.168.1.183"
2023-11-06 11:59:12.567832969  [INFO] Starting go2rtc...
2023-11-06 11:59:12.811600863  11:59:12.811 INF go2rtc version 1.8.1 linux/arm64
2023-11-06 11:59:12.812153059  11:59:12.812 INF [api] listen addr=0.0.0.0:1984
2023-11-06 11:59:12.812891872  11:59:12.812 INF [rtsp] listen addr=0.0.0.0:8554
2023-11-06 11:59:12.813546517  11:59:12.813 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-11-06 11:59:16.950562749  2023/11/06 11:59:16 [error] 154#154: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /ws HTTP/1.1", upstream: "http://127.0.0.1:5002/", host: "cam.lan"
2023-11-06 11:59:16.951415679  172.17.0.1 - - [06/Nov/2023:11:59:16 +0200] "GET /ws HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0" "192.168.1.183"
2023-11-06 11:59:17.828998880  [2023-11-06 11:59:17] frigate.app                    INFO    : Starting Frigate (0.13.0-89dd114)
2023-11-06 11:59:19.004313539  [2023-11-06 11:59:19] peewee_migrate.logs            INFO    : Starting migrations
2023-11-06 11:59:19.020734200  [2023-11-06 11:59:19] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-11-06 11:59:19.034766961  [2023-11-06 11:59:19] frigate.app                    INFO    : Recording process started: 318
2023-11-06 11:59:19.043523445  [2023-11-06 11:59:19] frigate.app                    INFO    : go2rtc process pid: 100
2023-11-06 11:59:19.102034107  [2023-11-06 11:59:19] detector.tensorrt              INFO    : Starting detection process: 327
2023-11-06 11:59:19.137500311  [2023-11-06 11:59:19] frigate.app                    INFO    : Output process started: 329
2023-11-06 11:59:19.347282857  [2023-11-06 11:59:19] frigate.app                    INFO    : Camera processor started for backyard: 347
2023-11-06 11:59:19.364130086  [2023-11-06 11:59:19] frigate.app                    INFO    : Camera processor started for front: 348
2023-11-06 11:59:19.380412568  [2023-11-06 11:59:19] frigate.app                    INFO    : Capture process started for backyard: 350
2023-11-06 11:59:19.396442494  [2023-11-06 11:59:19] frigate.app                    INFO    : Capture process started for front: 354
2023-11-06 11:59:21.254100527  [INFO] Starting go2rtc healthcheck service...
2023-11-06 11:59:22.514849011  [2023-11-06 11:59:22] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +225, GPU +0, now: CPU 282, GPU 3888 (MiB)
2023-11-06 11:59:22.652052926  [2023-11-06 11:59:22] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 91 MiB
2023-11-06 11:59:25.370374644  [2023-11-06 11:59:25] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +158, GPU +0, now: CPU 540, GPU 3887 (MiB)
2023-11-06 11:59:28.639919771  [2023-11-06 11:59:28] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +241, GPU -2, now: CPU 781, GPU 3885 (MiB)
2023-11-06 11:59:28.687194120  [2023-11-06 11:59:28] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +89, now: CPU 0, GPU 89 (MiB)
2023-11-06 11:59:28.772109393  [2023-11-06 11:59:28] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 690, GPU 3793 (MiB)
2023-11-06 11:59:28.790935454  [2023-11-06 11:59:28] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +1, now: CPU 690, GPU 3794 (MiB)
2023-11-06 11:59:28.871848064  [2023-11-06 11:59:28] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +83, now: CPU 0, GPU 172 (MiB)
2023-11-06 11:59:29.108749035  Process detector:tensorrt:
2023-11-06 11:59:29.110833909  Traceback (most recent call last):
2023-11-06 11:59:29.110844430    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-11-06 11:59:29.110847243      self.run()
2023-11-06 11:59:29.110850993    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-11-06 11:59:29.110861097      self._target(*self._args, **self._kwargs)
2023-11-06 11:59:29.110865212    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2023-11-06 11:59:29.110978859      detections = object_detector.detect_raw(input_frame)
2023-11-06 11:59:29.110987089    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2023-11-06 11:59:29.110990787      return self.detect_api.detect_raw(tensor_input=tensor_input)
2023-11-06 11:59:29.110994589    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 307, in detect_raw
2023-11-06 11:59:29.111027350      raw_detections[:, 4] = raw_detections[:, 4] * raw_detections[:, 6]
2023-11-06 11:59:29.111031517  TypeError: list indices must be integers or slices, not tuple
2023-11-06 11:59:39.626052957  [2023-11-06 11:59:39] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2023-11-06 11:59:39.668509839  [2023-11-06 11:59:39] detector.tensorrt              INFO    : Starting detection process: 449
2023-11-06 11:59:41.417302207  [2023-11-06 11:59:41] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +225, GPU +0, now: CPU 302, GPU 3539 (MiB)
2023-11-06 11:59:41.545939485  [2023-11-06 11:59:41] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 91 MiB
2023-11-06 11:59:42.892271545  [2023-11-06 11:59:42] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +158, GPU +160, now: CPU 561, GPU 3804 (MiB)
2023-11-06 11:59:44.599711478  [2023-11-06 11:59:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +240, GPU +38, now: CPU 801, GPU 3842 (MiB)
2023-11-06 11:59:44.604013625  [2023-11-06 11:59:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +89, now: CPU 0, GPU 89 (MiB)
2023-11-06 11:59:44.678879895  [2023-11-06 11:59:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 710, GPU 3752 (MiB)
2023-11-06 11:59:44.695845200  [2023-11-06 11:59:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +0, now: CPU 710, GPU 3752 (MiB)
2023-11-06 11:59:44.712283049  [2023-11-06 11:59:44] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +83, now: CPU 0, GPU 172 (MiB)
2023-11-06 11:59:44.832089310  Process detector:tensorrt:
2023-11-06 11:59:44.834763725  Traceback (most recent call last):
2023-11-06 11:59:44.834838674    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-11-06 11:59:44.834843049      self.run()
2023-11-06 11:59:44.834847320    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-11-06 11:59:44.834850653      self._target(*self._args, **self._kwargs)
2023-11-06 11:59:44.834875602    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2023-11-06 11:59:44.834879352      detections = object_detector.detect_raw(input_frame)
2023-11-06 11:59:44.834882737    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2023-11-06 11:59:44.834885862      return self.detect_api.detect_raw(tensor_input=tensor_input)
2023-11-06 11:59:44.834889352    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 307, in detect_raw
2023-11-06 11:59:44.834892841      raw_detections[:, 4] = raw_detections[:, 4] * raw_detections[:, 6]
2023-11-06 11:59:44.834913883  TypeError: list indices must be integers or slices, not tuple
2023-11-06 11:59:49.642929066  [2023-11-06 11:59:49] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

Other

**Comment by NickM-27** [comment] 2023-11-06 13:01
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/8246

any info that can be provided there about specifically when the issue started would be greatly appreciated

**Closed by NickM-27** 2023-11-06 13:01 UTC
Labels: duplicate, support, triage

**Comment by NickM-27** [comment] 2023-11-06 15:01
Oh I misunderstood the issue, thanks. So you are saying that `-jp4` worked under beta3?

**Comment by ramunasd** [comment] 2023-11-06 16:51
Yes, beta3 worked fine.

**Comment by NickM-27** [comment] 2023-11-09 16:10
It's already been fixed in dev
