### ISSUE TITLE
Convert H265 to H264 only on playback

### ISSUE THREAD

**Issue by gregordickie** [blakeblackshear/frigate#3807] opened 2022-09-09 20:59 UTC
Frigate is pretty cool. 

I've just bought a Reolink camera that ONLY supports H265 on the main stream. It would be really cool if we could have a hook to run an ffmpeg conversion only when trying to play back the high res stream on an incompatible browser rather than doing it for every recording (considering most of them will not be looked at).

Is that something possible to add (minus the browser detection)? Or is it even possible now?

Thanks a lot,
Greg

**Comment by NickM-27** [comment] 2022-09-09 21:19
I believe this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2243

The plan is to implement a post-processing stage that will support a number of different options like h265 -> h264 as well as things like time-lapses of the event, etc.

Either way, I don't think it will be done on demand as the latency would be too high especially for longer clips. 

Let me know if you disagree, but I believe this is a duplicate of the above linked issue and feel free to add your specific comments / ideas on that issue. I'll close this as duplicate unless you disagree.

**Comment by NickM-27** [comment] 2022-09-09 21:22
It is possible now as in you could do it yourself, frigate does not currently do it automatically.

**Comment by gregordickie** [comment] 2022-09-09 21:30
It does seem like a similar use case to 2243. I'm good with closing as a duplicate. Thanks you very much for the (insanely) quick reply!

**Comment by NickM-27** [comment] 2022-09-09 21:30
Closing as duplicate

**Closed by NickM-27** 2022-09-09 21:30 UTC
Labels: enhancement
