### ISSUE TITLE
Relative coordinates for define regions

### ISSUE THREAD

**Issue by pedrxd** [blakeblackshear/frigate#7404] opened 2023-08-06 16:59 UTC
**Describe what you are trying to accomplish and why in non technical terms**
Currently the coordinates on configuration are saved as absolute values over the image size. The problem with this is that if you change the image resolution, the coordinates become invalid and you should reconfigure zones and masks.

**Describe the solution you'd like**
To solve this problem, a relative coordinate to the size of the image can be used. The values are from 0 to 1, where 0 is the first pixel and 1 is the maximum height or width. 

Here a table with examples on a image of 1920x1080:
| Relatives | Absolutes |
| ---  | --- |
|0,0 | 0,0|
|1,1| 1920,1080|
|0.5,0.5 | 960,540|
|0.9,0.1 | 1728,108|

The conversion is trivial:
```
<relative_x> = <selected x pixel>/<image size x>
<relative_y> = <selected y pixel>/<image size y>

<selected x pixel> = <relative_x>*<image size x>
<selected y pixel> = <relative_y>*<image size y>
```

With this change, you could freely change the resolution of the image as long as you keep the ratio. For example, when you need to change resolution for performance reasons, you do not have to reconfigure all masks and zones.

**Comment by NickM-27** [comment] 2023-08-06 17:08
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/6309

**Closed by NickM-27** 2023-08-06 17:08 UTC
Labels: duplicate, enhancement
