### ISSUE TITLE
Update Python to 3.11 and Coral-related libraries

### ISSUE THREAD

**Issue by Te-eMster** [blakeblackshear/frigate#10885] opened 2024-04-08 17:09 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use up to date versions of python,libedgetpu,pycoral in the Frigate-Docker-Container.

**Describe the solution you'd like**
- Update Python-version to 3.11
- Update tflite-Models from "release-frogfish" to "release-grouper" (or newer if there are newer models)
- Update libedgetpu, tflite-runtime and pycoral to latest releases: 
- https://github.com/feranick/libedgetpu/releases/tag/16.0TF2.16.1-1
- https://github.com/feranick/TFlite-builds/releases/tag/v.2.16.1
- https://github.com/feranick/pycoral/releases/tag/v2.0.1TF2.16.1

**Describe alternatives you've considered**
- I can't change all Dockerfiles and dependency scripts myself as I have no overview of them :-)

**Additional context**
The long abandoned Coral-packages just lately received a little revival. It might be a good idea to implement this progress here as it might encourage devs to keep working on those packages.

**Comment by NickM-27** [comment] 2024-04-08 17:24
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/4394

updating would not only include updating python but that would also require updating the version of debian that is used. This would also require that all tensorrt, openvino, etc. libraries also supported newer versions of python. This will be an incredible amount of work and not something that will be done for the next release

**Closed by NickM-27** 2024-04-08 17:24 UTC
Labels: duplicate, enhancement
