### ISSUE TITLE
Possibility to delete multiple Events at once

### ISSUE THREAD

**Issue by AbDhops** [blakeblackshear/frigate#2702] opened 2022-01-24 19:52 UTC
**Describe what you are trying to accomplish and why in non technical terms**
Frigate detects multiple events. And those appear as a form of list under events. From the thumbnail it is possible to judge the importance of event. However, for not intreasted events, one has to open the event, and then click "delete" button to delte the event. Instead it shall be possible to select multiple events and delete them in one go. 

**Describe the solution you'd like**
Simply add "select" button for each event. And common "Delete" button clicking which selected events will be deleted.

**Describe alternatives you've considered**
There is not alternative

**Additional context**
None.

**Comment by blakeblackshear** [comment] 2022-01-25 01:23
duplicate of #2063

**Closed by blakeblackshear** 2022-01-25 01:23 UTC
Labels: enhancement
