### ISSUE TITLE
Disable Camera/Turn off Button

### ISSUE THREAD

**Issue by bubba925** [blakeblackshear/frigate#12299] opened 2024-07-04 17:48 UTC
With the new beta, the ability to disable motion and recording and such is nice. What about a button that disables the camera entirely/maybe a schedule? We have people house sitting and I thought it would be nice to be able to turn off the only indoor camera we have in the common space just for the increased privacy for them.

**Comment by NickM-27** [comment] 2024-07-04 17:55
This is a duplicate of #1911

**Closed** 2024-07-04 17:55 UTC
Labels: enhancement
