### ISSUE TITLE
Exclude ONVIF control panel from Birdseye view if no controllable camera included

### ISSUE THREAD

**Issue by Plawasan** [blakeblackshear/frigate#9989] opened 2024-02-23 08:55 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I have 6 cameras in my setup (5 external, 1 babycam), 4 of the external ones included in birdseye view. Only the babycam has onvif controls set up however the control panel for it still show up next to birdseye, significantly reducing its size:

![image](https://github.com/blakeblackshear/frigate/assets/73796046/f8f0c063-adca-4b93-a3fd-1642e2486de2)

**Describe the solution you'd like**
Only show the Control Panel if the camera is included in Birdseye or move the controls below the image to give it more space

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thanks!

**Comment by NickM-27** [comment] 2024-02-23 16:03
I'm going to consider this a duplicate of https://github.com/blakeblackshear/frigate/issues/7996 as it is the same idea

feel free to leave a 👍 on that request

**Closed by NickM-27** 2024-02-23 16:03 UTC
Labels: duplicate, enhancement
