### ISSUE TITLE
Only record if object is in frame for X seconds

### ISSUE THREAD

**Issue by Inrego** [blakeblackshear/frigate#6302] opened 2023-04-28 05:10 UTC
**Describe what you are trying to accomplish and why in non technical terms**
My house is near a trafficked road. Many cars pass during the day, and Frigate is recording each and every one of them. I want to be able to only record/notify about cars/people who stop at my house.

**Describe the solution you'd like**
A solution to this, could be a config to delay recording/notification until an object has been in the frame/zone for X amount of seconds. For example configuring Frigate to start recording and notifying about detected car when the car has been in the frame for 2 seconds. This way, passing cars would not be picked up since they're in the frame for less than 2 seconds.

**Describe alternatives you've considered**
My reolink cameras also have built-in AI detection with this feature. I've considered making a HA automation that only enables recording in Frigate after the camera has detected an object for 2 seconds. However, I'm considered about delays in such a setup. Agent DVR has an option to use the Reolink built-in AI for motion detection, which actually worked quite good for this case.

**Comment by blakeblackshear** [comment] 2023-04-28 10:57
There is a section in the docs for this already: https://docs.frigate.video/configuration/zones#restricting-events-to-specific-zones

**Comment by Inrego** [comment] 2023-04-28 11:13
To elaborate a little further. In my neighborhood there are cases where vans drive very slowly to have a good look at what's worth stealing.
We've recently become victims, and they stole some very expensive equipment from our yard after breaking through our fence. In the future, we'd like to be notified and record video if someone are lurking at our house

**Comment by NickM-27** [comment] 2023-04-28 11:44
You can definitely use MQTT to send notifications only when a vehicle loiters, but I don't think there's currently a way to differentiate "without pulling into my driveway"

In any case, this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2397

**Comment by Inrego** [comment] 2023-04-28 11:50
> You can definitely use MQTT to send notifications only when a vehicle loiters, but I don't think there's currently a way to differentiate "without pulling into my driveway"
> 
> In any case, this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2397

Right. Didn't find that. I've subscribed to that issue

**Closed** 2023-04-28 11:56 UTC
Labels: duplicate, enhancement
