### ISSUE TITLE
Dual Storage Path Events and Continuous

### ISSUE THREAD

**Issue by ckglobalroaming** [blakeblackshear/frigate#9950] opened 2024-02-21 02:07 UTC
Sorry if this already exists.

I have NVME for OS and Event storage with Coral TPU and is amazing. Can we add a second continuos storage recording path for always on recording of the camera streams and shove it down onto good old spining large disk for long term retention?

Tiered Fast Storage shor transactional events and Spinning high volume for long term review and retention

How would that be viewable?

Putting it out there. Thanks

**Comment by NickM-27** [comment] 2024-02-21 04:14
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3673

Also, there are many solutions for this outside of frigate. I have a setup like this using unraid which uses fuse.fs

**Closed** 2024-02-21 04:14 UTC
Labels: enhancement
