### ISSUE TITLE
Fallback to CPU detector when Coral is unplugged (e.g. accidentally)

### ISSUE THREAD

**Issue by Dzhuneyt** [blakeblackshear/frigate#13298] opened 2024-08-23 18:09 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I have a Synology NAS with Coral USB attached, but kids often disconnect it, which crashes the whole detector and camera feeds go dark. Instead, Frigate should "fallback" to the CPU detector or have a way of defining multiple detectors with a priority (use first, but fallback to second, if not available).

**Describe the solution you'd like**
Fallback to CPU detector if Coral detector is configured, but not available.

**Describe alternatives you've considered**
Ability to declare Coral and CPU detector at the same time in the config, but prioritize the Coral one at runtime.

**Comment by NickM-27** [comment] 2024-08-23 18:18
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/9106

**Closed** 2024-08-23 18:18 UTC
Labels: duplicate, enhancement
