### ISSUE TITLE
Delaying the Deletion of Old Files Untill a Set Time

### ISSUE THREAD

**Issue by WaffleMaster22** [blakeblackshear/frigate#14842] opened 2024-11-07 04:14 UTC
I want to be able to delay the deletion of old files untill a specific time of the day and then I want all the old files to delete at once when the set time arrives. This allows my HDDs to not have to spin up until the set date where all the old files get deleted at once. I would like an option somewhere to set a time for the files to be deleted instead of them deleting individually as soon as the retention period is up. The only other way I can think of is to set a cron job on unraid to delete old frigate files at a set time, but this would result to lots of missing files in frigate.

**Comment by NickM-27** [comment] 2024-11-07 04:19
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/2365

**Closed** 2024-11-07 04:20 UTC
Labels: duplicate, enhancement
