### ISSUE TITLE
[Feature Request] Multiple Retain Rules

### ISSUE THREAD

**Issue by joeShuff** [blakeblackshear/frigate#2966] opened 2022-03-14 17:56 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to define multiple retain rules for a camera so that I can save storage space in the long run but not lose anything important. For example:
For 7 days keep all footage `record -> retain -> mode = all`.
For 14 days keep all motion footage `record -> retain -> mode = motion`.
For 31 days keep all events footage `record -> retain -> move = active_objects`.

My understanding is that everything in `active_objects` is a subset of everything in `motion` which is a subset of `all` so as time passes it will slowly get rid of "useless" footage to save space. 

**Describe the solution you'd like**
To be able to define multiple rules for retention for a cameras config. e.g.

```
camera:
  record:
      retain:
          - days: 7
            mode: all
          - days: 14
            mode: motion
          - days: 31
            mode: active_objects
```

**Describe alternatives you've considered**
I've considered just using `active_objects` for event retention and `all` for record but again this could lose some important data. Unfortunately I've had to wade through my footage of a camera to get evidence for the police and I was lucky that I set the `record` retention so high because it wasn't an event but would have been motion. However leaving `all` on record builds up a lot of useless (motionless) footage.

**Comment by NickM-27** [comment] 2022-03-14 17:59
Duplicate of https://github.com/blakeblackshear/frigate/issues/2590

**Comment by joeShuff** [comment] 2022-03-14 18:03
Excellent - I thought there would be an issue for this already but couldn't find it. I see that one is pinned so feel free to close this one if you feel necessary.

**Comment by NickM-27** [comment] 2022-03-14 18:05
If you can close and add any extra context to the other ticket (if you'd like) that would be good. I'm just a contributor so I don't have the superpowers to close 👍

**Closed** 2022-03-14 18:17 UTC
Labels: enhancement
