### ISSUE TITLE
Run detection on image before sending to Frigate+

### ISSUE THREAD

**Issue by knobunc** [blakeblackshear/frigate#12605] opened 2024-07-25 12:33 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have full types and boundaries visible in training images to be sent Frigate+ so that I can more easily and accurately train.

I have several cars that are always present on one of my more active cameras, so when I need to train an image from that camera, I have to accurately select the car and license plates, along with whatever I am really training for.  Often two people, their faces, and a dog.

It would be excellent if all of that data could be sent to Frigate+ rather than just the one boundary and type that happens today.

**Describe the solution you'd like**
I think it would make sense to run a detection for all types and boundaries visible in the image locally before it is sent to Frigate+.

**Describe alternatives you've considered**
The Frigate+ server could run the detection, but that needs a bunch of computation and needs the model to be present on the server along with acceleration hardware.

**Comment by NickM-27** [comment] 2024-07-25 12:38
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/8229

**Closed by NickM-27** 2024-07-25 12:38 UTC
Labels: duplicate, enhancement
