### ISSUE TITLE
KYC feature for frigate

### ISSUE THREAD

**Issue by SajjadTofighy** [blakeblackshear/frigate#12510] opened 2024-07-19 06:26 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to set up a system where I can recognize My special customers by their faces. By uploading a photo of a customer's face, I want to be able to identify them whenever they visit. Over time, this system can build a more complete profile of each customer based on their facial features and other interactions.

**Describe the solution you'd like**
**Uploading Face Images as Person IDs:** You should be able to upload photos of your customers' faces to create a unique identification profile for each person.
**Using a Face Recognition Model to Check Against a KYC List:** The system should use a face recognition model to compare the uploaded photos with a list of known customers (KYC - Know Your Customer) to verify their identity.
Sending Alerts or Alarms to Operators: If a recognized customer is identified, the system should send an alert or alarm to notify the operator.

** Why its essential**
By implementing these features, you can enhance customer service and security by quickly recognizing your special customers as they interact with your business.

**Comment by NickM-27** [comment] 2024-07-19 11:51
You can already do something like this with double take https://github.com/jakowenko/double-take

This is a duplicate of https://github.com/blakeblackshear/frigate/issues/260

**Closed** 2024-07-19 11:52 UTC
Labels: duplicate, enhancement
