### ISSUE TITLE
[RC2]: invalid duration 0 must be positive while sending to client (opening clips of event)

### ISSUE THREAD

**Issue by ghust** [blakeblackshear/frigate#1681] opened 2021-09-02 06:48 UTC
**Describe the bug**
When opening an event, viewer hands with "The media could not be loaded, either because server or network failed or because the format is not supported".

nginx errorlog entry:

*12 media_set_parse_durations: invalid duration 0 must be positive while sending to client, client: 10.0.0.213, server: , request: "GET /vod/event/1630561583.321443-z3bde5/index.m3u8 HTTP/1.1", host: "xxxxxx:5123", referrer: "http://xxxxxxx:5123/events"

**Version of frigate**
0.9.0-46fe06e

**Config file**
Include your full config file wrapped in triple back ticks.
```ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
mqtt:
  host: mqtt.server
  port: 1883
  user: #########
  password: ##########
record:
  enabled: true
  retain_days: 60

cameras:
  front:
    clips:
      enabled: True
      pre_capture: 30
      post_capture: 30
      objects:
        - person
      retain:
        default: 365
    detect:
      width: 2560
      height: 1920
      fps: 5
      enabled: true

    ffmpeg:
      inputs:
        - path: ########
          roles:
            - detect
            - record
            - rtmp
    objects:
     filters:
      person:
       mask:
        - 2560,0,2539,553,1067,254,1035,0
detectors:
  coral:
    type: edgetpu
    device: usb

motion:
  mask:
    - 1855,445,2560,420,2560,459,2560,0,1050,0,1061,299,1264,299
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```{"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":217}},"front":{"camera_fps":0.0,"capture_pid":224,"detection_fps":0.0,"pid":222,"process_fps":0.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":66.8,"mount_type":"tmpfs","total":67.1,"used":0.3},"/media/frigate/clips":{"free":310514.6,"mount_type":"ext4","total":1969008.5,"used":1558474.1},"/media/frigate/recordings":{"free":310514.6,"mount_type":"ext4","total":1969008.5,"used":1558474.1},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"uptime":269,"version":"0.9.0-46fe06e"}}
```

**FFprobe from your camera**

Run the following command and paste output below
```

ffprobe version 3.4.8-0ubuntu0.2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[rtsp @ 0x55e9f3fda080] max delay reached. need to consume packet
[rtsp @ 0x55e9f3fda080] RTP: missed 32 packets
Input #0, rtsp, from 'url':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 30 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

**Screenshots**
https://i.imgur.com/32XQGWG.png
https://i.imgur.com/LA8gCt2.png

**Computer Hardware**
 - OS: Ubuntu
 - Install method: Compose
 - Virtualization: NA
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolink
 - Model: RLC410
 - Resolution: [e.g. 720p]
 - FPS: 5

**Additional context**

**Comment by tve** [comment] 2021-09-28 14:59
Same issue here. Possibly related to #1862

**Comment by tve** [comment] 2021-11-21 00:17
I continue having this issue... Sadly #1862 has been closed by the bot, so here goes:
Error in browser:
`The media could not be loaded, either because server or network failed or because the format is not supported`
URL requested: 
`/vod/2021-11/20/00/cam5/index.m3u8`
Error in nginx log:
```
*41 media_set_parse_durations: invalid duration 0 must be positive while sending to client,
client: 192.168.0.2, server: , request: "GET /vod/2021-11/20/00/cam5/index.m3u8 HTTP/1.1",
host: "core2:5000", referrer: "http://core2:5000/recording/cam5"
```
First file in that directory:
```
4552 -rw-r--r-- 1 root root 4657550 Nov 20 00:01 00.00.mp4
```
ffmpeg length (as requested in #1862)"
```
# ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 /media/frigate/recordings/2021-11/20/00/cam5/00*
60.000000
```
I ran the ffmpeg command in a for loop on all files in the directory and they all have 60 seconds.
Then I logged what `vod_ts` https://github.com/blakeblackshear/frigate/blob/release-0.10.0/frigate/http.py#L668 returns:
```
[2021-11-20 15:59:12] frigate.http                   INFO    : /vod returns: {'cache': True, 'discontinuity': False, 'durati
ons': [0, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60...
```
Spot the zero... What's the path?
```
[{'type': 'source', 'path': '/media/frigate/recordings/2021-11/19/23/cam5/59.00.mp4'
```
Aha, so it's the last recording of the previous hour and that doesn't exist, prob 'cause I had a filesystem issue.
I made the following patch:
```
--- a/frigate/http.py
+++ b/frigate/http.py
@@ -658,13 +658,22 @@ def vod_ts(camera, start_ts, end_ts):
         # Determine if we need to end the last clip early
         if recording.end_time > end_ts:
             duration -= int((recording.end_time - end_ts) * 1000)
-        clips.append(clip)
-        durations.append(duration)
+        if duration > 0:
+            clips.append(clip)
+            durations.append(duration)
+        else:
+            logger.warning("Recording clip %s is missing or empty", recording.path)

     if not clips:
         return "No recordings found.", 404
```
That fixes this problem, but I'm still having very similar issues due to missing files. Basically my DB and filesystem got out of sync due to a filesystem full event where I had to delete a bunch of stuff to be able to keep going. Given the nature of frigate I'm pretty sure I'm not the first or the last one to encounter this type of issue, so it would be good to chip away at these errors so frigate is more lenient and manages to keep going and serve up what's there instead of barfing.

**Comment by blakeblackshear** [comment] 2021-11-21 12:38
@tve thanks for tracking down some of the details here. I will see if I can reproduce this.

**Comment by tve** [comment] 2021-11-21 18:35
You're welcome, I can do more digging if you have specifics. I believe that "under normal operation" there most likely is no bug. The problems appear when something goes awry and it would be nice for frigate to recover/cover-up gracefully. That would also reduce the number of issues filed 'cause users don't get any meaningful error message.
Given the data volume and data rate of recordings things are guaranteed to go awry regularly... In my case I was recording to an SDcard and the USB stack decided to create a hiccup which caused the SDcard to be unmounted and then the recordings filled up the root disk... (I've now changed to recording to the root SSD and moving old recordings to the SDcard nightly, maybe I'll try mounting the SDcard on /media/recordings instead of /media...)

**Comment by blakeblackshear** [comment] 2021-11-21 19:12
I added two changes in beta4 of 0.10.0 related to this. Every 10 minutes, any recordings in the database that are no longer found on disk are deleted. I also added the duration check. That section of code is purely driven off the database, so it wouldn't matter if the files existed. It would of course fail to play when playback was started if it was expecting files to be there.

**Comment by tve** [comment] 2021-11-21 19:34
Hmm, so this means that if there is any 10 minute glitch with a mounted drive the recordings are effectively lost?

**Comment by blakeblackshear** [comment] 2021-11-21 20:21
If there was a glitch, the operation to check the disk for recordings would also fail. There are definitely scenarios where you could drop all your recording information from the database, but I think that's less likely than running into errors where it's expecting recordings to be there and they aren't.

**Comment by NickM-27** [comment] 2024-04-05 13:34
Closing as I don't believe this is relevant anymore, information is stored in the DB and sent as part of the vod request

**Closed by NickM-27** 2024-04-05 13:34 UTC
Labels: bug, pinned
