### ISSUE TITLE
Add ability to trigger motion based recording from external sensor

### ISSUE THREAD

**Issue by bradmck** [blakeblackshear/frigate#1888] opened 2021-09-30 11:06 UTC
First - thank you for this impressive project.  Really nice work.

**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to trigger a motion event based on input from an external sensor.  This would be similar to how many commercial NVRs have dry-contact inputs that can be used to trigger recording.

**Describe the solution you'd like**
Ideally Home Assistant would see the motion event from the external (to Frigate) sensor and could call a Frigate service to start a motion event.  So start recording and label that recording as Motion.  The service call should probably support sending the desired recording length as part of the call.  The type of motion sensor shouldn't matter - could be Zwave, Zigbee, ESPHome, etc - anything that HA supports.  It might be nice to be able to send the event-type label as part of the service call?  So I'm not asking for Frigate to work directly with a motion sensor - I'd just like to have a Service I can call from Home Assistant to trigger a recording event and to be able to Label it as Motion (or again, ideally I could send the label in the service call).

I did look at the API docs and didn't see a way to do this.  If I missed something my apologies.  I also did try searching but didn't see this talked about.

**Describe alternatives you've considered**

**Additional context**

**Comment by blakeblackshear** [comment] 2021-09-30 11:19
Duplicate of #1063

**Closed by blakeblackshear** 2021-09-30 11:19 UTC
Labels: enhancement
