### ISSUE TITLE
[Support]: Frigate 0.12.0 randomly crashes

### ISSUE THREAD

**Issue by my-umd** [blakeblackshear/frigate#5976] opened 2023-04-10 20:05 UTC
### Describe the problem you are having

Experienced twice during the past two days.  The docker container seem not responding.  If I try to stop it, I get an error message saying that the container cannot be stopped ("tried to kill the container, but did not receive an exit event").  I see 'go2rtc-healthcheck service exited with code 256 (by signal 15)'.  Then it says 'service go2rtc-healthcheck successfully stopped'.  I did not have this issue when running 0.12.0-rc1 (I had rc1 running for about two weeks before started using the official 0.12.0 release yesterday).

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
# I have 6 cameras setting up the same way.  Only present settings for one here
mqtt:
  host: 192.168.xxx.xxx

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

birdseye:
  enabled: True 
  mode: continuous

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  streams:
    front_door:
      - rtsp://xxxx:xxxx@192.168.xxx.xxx/live
      - ffmpeg:front_door#audio=aac

  webrtc:
    candidates:
      - 192.168.xxx.xxxx:8555
      - stun:8555

detect:
  enabled: True
  width: 1920
  height: 1080

rtmp:
  enabled: True

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - rtmp
      output_args:
        record: preset-record-generic-audio-copy
```

### Relevant log output

```shell
The Web UI crashed, I have no way to get any log.
```

### FFprobe output from your camera

```shell
Container crashed.  I cannon access Frigate Web UI, or open a shell to access the container.
```

### Frigate stats

```json
Frigate Web UI crashed.  Cannot reach the end point.
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

Other

### Network connection

Wireless

### Camera make and model

Wyze Cam V2, V3 on rtsp firmware

### Any other information that may be helpful

The application was run on a QNAP NAS with J3455 CPU.  This is the command to create the container:
`docker run --name=frigate --shm-size=256m --restart=unless-stopped --env=TZ=America/New_York --env=LIBVA_DRIVER_NAME=i965 --env=FRIGATE_RTSP_PASSWORD=xxxxxx --volume=/share/Container/frigate/config:/config:rw --volume=/share/share_vol2/frigate/media:/media/frigate:rw --network=bridge --privileged --workdir=/opt/frigate -p 4xxxx:1935 -p 4xxxx:5000 -p 4xxxx:8554 -p 4xxxx:8555 -p 4xxxx:8555/udp --label='com.qnap.qcs.network.mode=nat' --label='com.qnap.qcs.gpu=False' --memory="4g" --cpus="2" --detach=true -t ghcr.io/blakeblackshear/frigate:0.12.0`
I used the same command to create 0.12.0-rc1 container.  Config files are identical in 0.12.0 and 0.12.0-rc1.

I know it is hard to debug without any logs.  I recall there was one object referencing from one of the cameras stayed at 'in progress' stage for very long time.  Not sure if this exhausted system resources.  But I would assume same thing also happened in 0.12.0-rc1, which never crashed.  Another observation is that, I ran the docker from QNAP's Container Station (similar thing to Portainer).  When Frigate crashed, Container Station lost control of it.  I had to turn off the NAS by pressing the power button.  There seems to be a hanging process.  When I run the `ps` command, the command just hangs there after showing some processes.

**Comment by my-umd** [comment] 2023-04-10 20:45
Thanks @NickM-27.  I am going to revert to rc1 just to see if I can reproduce.  I understand there shouldn't be much changes from rc1 to the official release.  Checking my NAS log, I see this from yesterday:
`Warning	2023-04-09	18:13:42	System	127.0.0.1	Hardware Status	Kernel	[Hardware Status] NAS out of memory. Started kill process: 4683 "ffmpeg". Disable some applications to free up memory, or expand the system memory.`
But I don't see the same message from today's crash.  I have 16G of RAM, should be plenty.

**Comment by idle-user** [comment] 2023-04-11 04:26
Just wanted to add to this, maybe related:

I installed frigate today and using a coral tpu (usb). Everything is going smooth after getting everything setup, but happened like 3 times today that my cpu usage spikes over 20.0 in top, and the memory runs out.

I have to fight to stop the container, but if it happens again I'll try to dig up some logs to share here.


Running on:

Synology DS1520+
Coral TPU (USB)
4 Cameras

Usual cpu usage: ~18%

**Comment by my-umd** [comment] 2023-04-11 10:45
> Just wanted to add to this, maybe related:
> 
> I installed frigate today and using a coral tpu (usb). Everything is going smooth after getting everything setup, but happened like 3 times today that my cpu usage spikes over 20.0 in top, and the memory runs out.
> 
> I have to fight to stop the container, but if it happens again I'll try to dig up some logs to share here.
> 
> Running on:
> 
> Synology DS1520+ Coral TPU (USB) 4 Cameras
> 
> Usual cpu usage: ~18%

Thanks.  Are you using 0.12.0 official release and go2rtc restreaming?  How much RAM do you have?  My 0.12.0-rc1 with go2rtc config crashed as well after around 10-11 hr running.  So I now have total of 3 crashes when using go2rtc.  I realized that my previous try of rc1, which lasted about two weeks, was using a config without go2rtc and restreaming.  I will revert to non-go2rtc and see.

**Comment by idle-user** [comment] 2023-04-11 17:09
> Thanks. Are you using 0.12.0 official release and go2rtc restreaming? 

Yes.

How much RAM do you have? My 0.12.0-rc1 with go2rtc config crashed as well after around 10-11 hr running. So I now have total of 3 crashes when using go2rtc. I realized that my previous try of rc1, which lasted about two weeks, was using a config without go2rtc and restreaming. I will revert to non-go2rtc and see.

The DS1520+ has 8GB of RAM.

My system overloads and runs out of memory within an hour. Since I have managed to stop it, I assume I avoid the crash you're facing?

I have a strong feeling it has to do with an RTSP Wyze camera I have. Ever since I have disabled the camera in the config, I have been running fine since yesterday. 

Still monitoring

**Comment by my-umd** [comment] 2023-04-11 19:16
@idle-user, thanks for your info..  Mind telling me what Wyze camera version that you disabled?  I have a mixture of 2 v2s and 4 v3s.
Looks my setup managed to run longer than yours.  I closely monitored it after I reverted to rc1 last night.  And I didn't observe any hike in CPU and/or RAM usage after about 5 hours.  Somehow, it then crashed during my sleep.  My NAS has J3455 CPU and 16G of RAM.  I limited CPU usage to 50% and RAM usage to 4G when creating the docker (pls see my docker run command in issue description).  It seems there was some memory leak somewhere.  Really not an expert on this.
I restarted official 0.12.0 docker release without go2rtc early this morning.  It has been running fairly stable for 8+ hours.  My gut feeling is that go2rtc + Wyze whatever version is doing something funky.

**Comment by idle-user** [comment] 2023-04-11 19:19
The Wyze cam is a v2 with the RTSP firmware

**Comment by idle-user** [comment] 2023-04-12 17:45
I wanted to provide an update, I'm trying out the [wyze-bridge project](https://github.com/mrlt8/docker-wyze-bridge).
I have a couple dumb wyze v2 cams I don't really pay much attention to, so I set them up, and looks to be working. 

I set wyze-bridge container to run on a separate pi I have, but it doesn't seem resource intensive so I might move it to the same stack I have frigate on later.

Only downside I see about the project is that it requires an internet connection to connect to the wyze servers, if I'm not mistaken. If LAN only is required, I guess the only options are the official RTSP firmware or the dafang hack.

**Comment by NickM-27** [comment] 2023-04-12 18:44
wyze docker bridge connects locally to the camera, just FYI @idle-user

**Comment by my-umd** [comment] 2023-04-13 00:13
Thanks @idle-user and @NickM-27.
I commented out go2rtc settings for my two Wyze v2, changed to directly access v2 camera stream under camera settings and restarted Frigate (i.e., I only have my 4 Wyze v3 using go2rtc this time).  It still crashed after ~12 hr.  So go2rtc does not like Wyze v3 either.  This time, I do see an out of memory log entry:
`2023-04-12 21:59:46.488651331  [2023-04-12 17:59:46] ffmpeg.garage_inside.detect    ERROR   : av_interleaved_write_frame(): Cannot allocate memory `
Also FFmpeg disappeared for all cameras, e.g.:
`2023-04-12 22:39:14.196401200  [2023-04-12 18:39:14] watchdog.drive_way                 INFO    : FFmpeg did not exit. Force killing..`.

So, as mentioned earlier, there seems to be a memory leak somewhere when go2rtc and Wyze cameras are both present.  I don't understand how this could happen though.  Because go2rtc seems only to copy streams.  Will these streams stay in RAM forever?  I have max. of 4G RAM allocated to Frigate docker container.  Not sure if it is too small.  Is there a guideline on how much RAM I need to use for a camera in go2rtc (like in shm-size case)?

I will have to go back to use a config file without any go2rtc settings, which I know was very stable.

**Comment by NickM-27** [comment] 2023-04-13 01:49
It is difficult to compare as it is not really apples to apples. But I have 4 cameras which means go2rtc is providing 4 streams, then I also have go2rtc using ffmpeg to downscale those streams to create new "sub streams" which equates to 8 streams total. It is using a total of 1GB RAM (including ffmpeg processes)

**Comment by lovelylain** [comment] 2023-04-13 06:03
Maybe helpful, when I restart my wifi, the camera will lost connection for a short time, then the frigate.capture process will eat much memory until no memory. So I have to write a script, when the swap is used exceeds a threshold, docker restart frigate.

**Comment by my-umd** [comment] 2023-04-18 20:22
Because my Frigate with go2rtc setting and with directly connecting to my cameras (i.e., I set up go2rtc in Frigate but do not use it) crashed after running for 10-12 hr.  To isolate the issue, I tried to set up a stand-alone go2rtc docker to see if it crashes.  I think this setup will mimic the go2rtc environment in my Frigate install.  I obtained go2rtc config for all my 6 Wyze v2 and v3 cameras from Frigate's go2rtc dashboard (for some reason, need to comment out "default_query:mp4") and created a stand-alone go2rtc (v1.2.0) docker (20% CPU, 2G RAM, 64M shm-size).  I was able to obtain a page that is identical to what is shown on Frigate go2rtc dashboard.  This stand-alone go2rtc docker kept running for more than one day without crashing.  Does this suggest that the crashing observed with Frigate plus go2rtc has little or nothing to do with Wyze cameras?

BTW, here are scenarios that I know so far:
1. Frigate docker + Wyze v2 and v3: working
2. Frigate docker + go2rtc + Wyze v2 and v3, without restreaming: crash after 10 hr due to out of memory
3. Frigate docker + go2rtc + Wyze v2 and v3, with restreaming: crash after 10 hr due to out of memory
4. go2rtc docker + Wyze v2 and v3 running together with Frigate docker + Wyze v2 and v3 (i.e., scenario 1): working

**Comment by NickM-27** [comment] 2023-04-18 20:25
users who have had issues like this have almost universally been using wyze cameras, no one else has reported it. also, what version of go2rtc were you running standalone, was it the same as frigate has?

I don't see how using it without restreaming would result in an out of memory issue, what is even using the memory? without this info, there is no action that can be taken

**Comment by my-umd** [comment] 2023-04-18 20:34
Thanks @NickM-27. As mentioned in my earlier comment, I installed go2rtc v1.2.0, same as what Frigate 0.12.0 uses.  It is hard for me to visualize how without restreaming would cause an out of memory issue as well.  My scenarios 4 should mimic scenarios 2.  I'm very confused.

**Comment by NickM-27** [comment] 2023-04-18 20:36
So, we need htop screenshots at the minimum to understand what is actually using memory

**Comment by idle-user** [comment] 2023-04-19 15:51
Histogram doesn't tell us much besides stating there was high-usage. 
As @NickM-27 mentioned, showing an `htop` of the processes is necessary to identify which processes is consuming the resources.

**Comment by HarlemSquirrel** [comment] 2023-04-19 16:51
In my case I don't think it was an over utilization of CPU or memory usage which is why I wanted to share the histogram

**Comment by my-umd** [comment] 2023-04-20 10:42
I cannot reproduce scenario 2 mentioned in my [early comment](https://github.com/blakeblackshear/frigate/issues/5976#issuecomment-1513750133).  I had it run 36 hr and seems still stable.  Sorry, I probably have messed up my memory, because I was trying different config combinations at the time.  However, from @HarlemSquirrel's comment, seems scenario 2 still fails in some system.
I am pretty sure scenario 3 ([from here](https://github.com/blakeblackshear/frigate/issues/5976#issuecomment-1513750133))  is a real issue.  And a couple of new issues (#6171 and #6174) might be the same, though they do not use the same installing method as mine.

**Comment by NickM-27** [comment] 2023-04-20 11:49
Okay, seeing as your issue has been running stable I'll close this. Anyone experiencing similar is recommended to create their own issue. It's too easy to say "this is my problem too" when it's actually unrelated. Creating a separate issue and providing all the requested info makes it much easier to find the problems.

**Closed by NickM-27** 2023-04-20 11:49 UTC
Labels: support, triage

**Comment by my-umd** [comment] 2023-04-20 14:03
Thanks @NickM-27.  I am fine to close it for now.  I created issue because go2rtc with restreaming kills my container (presumably due to out of memory).  I am currently using go2rtc without restreaming.
Because I have a stand-alone go2rtc docker installed in my system, would you suggest a way to mimic go2rtc restreaming in Frigate using my stand-alone go2rtc install?  I would like to try it out and hopefully to isolate the memory leak issue.

**Comment by NickM-27** [comment] 2023-04-20 14:05
I mean the restream part is identical, it's just the live view and birdseye that won't work. In any case, frigate runs go2rtc 1.2.0 and I think a more interesting test (from my perspective anyway) would be running frigate with g2rtc 1.3.2 (which you can do by adding the go2rtc binary in /config) and see if this still occurs

**Comment by my-umd** [comment] 2023-04-21 02:17
Thanks for the suggestion @NickM-27.  I set up Frigate to use go2rtc v1.3.2:
`2023-04-20 16:19:05.166278153  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-04-20 16:19:05.284738654  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-04-20 16:19:05.284784324  [INFO] Starting go2rtc...
2023-04-20 16:19:05.492290866  2023/04/20 12:19:05 [error] 134#134: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.3.3, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.x.x:xxxxx"
2023-04-20 16:19:05.502748940  10.0.3.3 - - [20/Apr/2023:12:19:05 -0400] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2022.12.8 aiohttp/3.8.1 Python/3.10" "-"
2023-04-20 16:19:05.529151083  12:19:05.528 INF go2rtc version 1.3.2 linux/amd64
2023-04-20 16:19:05.530955627  12:19:05.529 INF [api] listen addr=:1984
2023-04-20 16:19:05.530963519  12:19:05.529 INF [rtsp] listen addr=:8554
2023-04-20 16:19:05.532936811  12:19:05.531 INF [srtp] listen addr=:8443
2023-04-20 16:19:05.532944630  12:19:05.531 INF [webrtc] listen addr=:8555/tcp`

After 3 hours, I see a lot of these warnings (every 10-15 seconds) from my two Wyze v2 cameras, e.g.,:
`2023-04-20 19:05:45.839012449  [2023-04-20 15:05:45] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/front_door-20230420150531.mp4
2023-04-20 19:05:55.846504432  [2023-04-20 15:05:55] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/front_door-20230420150542.mp4
`
I do not have `htop` installed in my system.  I closely monitored it this time, and found that the container crashed between 9-10 hours (most likely at 9.5 hr) after it's started.  Because I do not know the exact time it crashed, I could not take a `top` snapshot.

**Comment by my-umd** [comment] 2023-04-30 00:01
Unfortunately, using a config without restreaming finally crashed after 9 days.  Here is the summary of all scenarios that I observed so far:
1. Frigate docker + Wyze v2 and v3 (no go2rtc in config): working
2. Frigate docker + go2rtc + Wyze v2 and v3, without restreaming: crash after 9 days
3. Frigate docker + go2rtc + Wyze v2 and v3, with restreaming: crash after 10 hr due to out of memory
4. go2rtc stand-alone docker + Wyze v2 and v3 running together with Frigate docker + Wyze v2 and v3 (i.e., scenario 1): working

Apparently, there is something hidden deeply with go2rtc integration that causes system instability, at least for my system.

**Comment by blakeblackshear** [comment] 2023-04-30 00:44
Go2rtc is incredibly simple. Since it's written in Go, it is entirely encapsulated in a single binary with zero external dependencies. The "integration" with frigate is literally just running that simple binary in the frigate container. It creates a config on startup and never interacts with it again after that. There aren't any options or things to change to try and fix this other than running a different version of go2rtc which you can do yourself.

**Comment by my-umd** [comment] 2023-04-30 09:22
> There aren't any options or things to change to try and fix this other than running a different version of go2rtc which you can do yourself.

Thanks @blakeblackshear for the explanation.  I did try [using go2rtc v1.3.2](https://github.com/blakeblackshear/frigate/issues/5976#issuecomment-1517161312)  before and got the same issue.  Just added it to my [summary](https://github.com/blakeblackshear/frigate/issues/5976#issuecomment-1528899832).

**Comment by my-umd** [comment] 2023-05-14 21:11
Tried using 1.5G tmpfs, 4G swap as hinted by [this comment](https://github.com/blakeblackshear/frigate/issues/6132#issuecomment-1531816431).  My container with go2rtc restreaming crashed much sooner (down from 9-10 hr to within 1 hr).
I installed htop in frigate container and observed the behavior with different config files.  I can see that the container does not use swap memory at all when using a config file with direct connecting to the cameras.  It uses swap memory when using a config file with go2rtc restreaming.  The swap usage increases overtime.  Not sure if it is a coincidence, I see such log when I see swap usage increases:
`2023-05-14 17:32:44.336472648  [2023-05-14 13:32:44] watchdog.garage_outside        INFO    : No frames received from garage_outside in 20 seconds. Exiting ffmpeg...
2023-05-14 17:32:44.336698343  [2023-05-14 13:32:44] watchdog.garage_outside        INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-14 17:33:14.395128310  [2023-05-14 13:33:14] watchdog.garage_outside        INFO    : FFmpeg did not exit. Force killing...
2023-05-14 17:33:16.140351377  [2023-05-14 13:33:16] frigate.video                  ERROR   : garage_outside: Unable to read frames from ffmpeg process.
2023-05-14 17:33:16.140909574  [2023-05-14 13:33:16] frigate.video                  ERROR   : garage_outside: ffmpeg process is not running. exiting capture thread...
2023-05-14 17:33:16.757536766  [2023-05-14 13:33:16] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/garage_outside-20230514133157.mp4: 0 - b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55eb41c926c0] moov atom not found\n/tmp/cache/garage_outside-20230514133157.mp4: Invalid data found when processing input\n'
2023-05-14 17:33:16.757547079  [2023-05-14 13:33:16] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/garage_outside-20230514133157.mp4
2023-05-14 17:33:26.142336991  [2023-05-14 13:33:26] watchdog.garage_outside        ERROR   : Ffmpeg process crashed unexpectedly for garage_outside.
2023-05-14 17:33:26.142346007  [2023-05-14 13:33:26] watchdog.garage_outside        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-14 17:33:26.142348885  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : [rtsp @ 0x55c8a9344100] RTP: PT=60: bad cseq 13b1 expected=5676
2023-05-14 17:33:26.142352545  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : [segment @ 0x55c8a94d10c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2023-05-14 17:33:26.142355112  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : [rtsp @ 0x55c8a9344100] RTP: PT=61: bad cseq 0d03 expected=16ad
2023-05-14 17:33:26.142357509  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : DTS 3261157973, next:268807000 st:1 invalid dropping
2023-05-14 17:33:26.142359904  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : PTS 3261157973, next:268807000 invalid dropping st:1
2023-05-14 17:33:26.142414749  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : DTS 3261158997, next:268871000 st:1 invalid dropping
2023-05-14 17:33:26.160511375  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : PTS 3261158997, next:268871000 invalid dropping st:1
2023-05-14 17:33:26.160519638  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : DTS 3261160021, next:268935000 st:1 invalid dropping
2023-05-14 17:33:26.160522371  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : PTS 3261160021, next:268935000 invalid dropping st:1
2023-05-14 17:33:26.160524793  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : DTS 3261161045, next:268999000 st:1 invalid dropping
2023-05-14 17:33:26.160527160  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : PTS 3261161045, next:268999000 invalid dropping st:1
2023-05-14 17:33:26.160529592  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : DTS 3261162069, next:269063000 st:1 invalid dropping
2023-05-14 17:33:26.160531905  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : PTS 3261162069, next:269063000 invalid dropping st:1
2023-05-14 17:33:26.160534348  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : DTS 3261163093, next:269127000 st:1 invalid dropping
2023-05-14 17:33:26.160536770  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : PTS 3261163093, next:269127000 invalid dropping st:1
2023-05-14 17:33:26.160539078  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : DTS 3261164117, next:269191000 st:1 invalid dropping
2023-05-14 17:33:26.160541486  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : PTS 3261164117, next:269191000 invalid dropping st:1
2023-05-14 17:33:26.160543787  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : DTS 3261165141, next:269255000 st:1 invalid dropping
2023-05-14 17:33:26.160546091  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : PTS 3261165141, next:269255000 invalid dropping st:1
2023-05-14 17:33:26.160548462  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : DTS 3261166165, next:269319000 st:1 invalid dropping
2023-05-14 17:33:26.160550784  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : PTS 3261166165, next:269319000 invalid dropping st:1
2023-05-14 17:33:26.160553437  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : [out_1_0 @ 0x55c8a943e240] 100 buffers queued in out_1_0, something may be wrong.
2023-05-14 17:33:26.160556113  [2023-05-14 13:33:26] ffmpeg.garage_outside.detect   ERROR   : [out_1_0 @ 0x55c8a943e240] 1000 buffers queued in out_1_0, something may be wrong.
2023-05-14 17:53:46.450174997  [2023-05-14 13:53:46] watchdog.garage_outside        INFO    : No frames received from garage_outside in 20 seconds. Exiting ffmpeg...
2023-05-14 17:53:46.450183271  [2023-05-14 13:53:46] watchdog.garage_outside        INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-14 17:54:16.511169255  [2023-05-14 13:54:16] watchdog.garage_outside        INFO    : FFmpeg did not exit. Force killing...
2023-05-14 17:54:18.100887530  [2023-05-14 13:54:18] frigate.video                  ERROR   : garage_outside: Unable to read frames from ffmpeg process.
2023-05-14 17:54:18.100896037  [2023-05-14 13:54:18] frigate.video                  ERROR   : garage_outside: ffmpeg process is not running. exiting capture thread...
2023-05-14 17:54:20.913934471  [2023-05-14 13:54:20] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/garage_outside-20230514135308.mp4: 0 - b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x555d999246c0] moov atom not found\n/tmp/cache/garage_outside-20230514135308.mp4: Invalid data found when processing input\n'
2023-05-14 17:54:20.913942947  [2023-05-14 13:54:20] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/garage_outside-20230514135308.mp4
2023-05-14 17:54:28.068287679  [2023-05-14 13:54:28] watchdog.garage_outside        ERROR   : Ffmpeg process crashed unexpectedly for garage_outside.
2023-05-14 17:54:28.068297913  [2023-05-14 13:54:28] watchdog.garage_outside        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-14 17:54:28.068300772  [2023-05-14 13:54:28] ffmpeg.garage_outside.detect   ERROR   : [rtsp @ 0x55605c3af100] RTP: PT=60: bad cseq ad92 expected=ea5c
2023-05-14 17:54:28.069266545  [2023-05-14 13:54:28] ffmpeg.garage_outside.detect   ERROR   : [out_1_0 @ 0x55605c4b9c40] 100 buffers queued in out_1_0, something may be wrong.
2023-05-14 17:54:28.070707532  [2023-05-14 13:54:28] ffmpeg.garage_outside.detect   ERROR   : [out_1_0 @ 0x55605c4b9c40] 1000 buffers queued in out_1_0, something may be wrong.`

Also noticed that there are 18 go2rtc processes in total (I have 6 cameras), see this screenshot:
![restreaming_go2rtc_processes](https://github.com/blakeblackshear/frigate/assets/27736698/31e3facf-6e75-42b1-a7d6-1303eead9f86)
Not sure if this is expected.

**Comment by NickM-27** [comment] 2023-05-14 21:18
I only see 5 go2rtc processes, the green are threads not processes.

**Comment by NickM-27** [comment] 2023-05-14 21:18
I'd be curious how go2rtc 1.5.0 runs. I've still as of yet been unable to reproduce any problem behavior and I run multiple processes for most cameras in go2rtc

**Comment by my-umd** [comment] 2023-05-14 22:43
> I only see 5 go2rtc processes, the green are threads not processes.
Oh, sorry.  My bad.

> I'd be curious how go2rtc 1.5.0 runs. I've still as of yet been unable to reproduce any problem behavior and I run multiple processes for most cameras in go2rtc
The container crashed within 5 minutes when using go2rtc 1.5.0.

BTW, it probably does not mean anything.  I forgot to grant execute permission on go2rtc on my first try with v1.5.0.  When I tried to start frigate container, it died within the same time frame.

**Comment by my-umd** [comment] 2023-05-15 00:13
Another observation is about the CPU load average.  With go2rtc restreaming, the CPU load average can go up to 10.  While when not using any go2rtc, the load average maintains at less than 6, usually in 4.xx range.

**Comment by NickM-27** [comment] 2023-05-15 00:14
yes, restreaming rtsp is an expensive task, that is not a surprise

**Comment by my-umd** [comment] 2023-05-15 00:21
> yes, restreaming rtsp is an expensive task, that is not a surprise

ah, I see.  Thanks for the explanation.
