### ISSUE TITLE
[Support]: Frigate always disables snapshots for one of my cameras

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#5552] opened 2023-02-20 14:59 UTC
### Describe the problem you are having

1. It's enabled in the config file
2. When Frigate starts, the snapshots comes disabled:

    ```
    frigate.comms.dispatcher       INFO    : Turning off snapshots for video_porteiro
    ```

3. If I enabled from UI it only stays enabled before next reboot
4. Same if I change from the Home Assistant switch

https://user-images.githubusercontent.com/29582865/220140216-4238c74e-f0f2-48a4-8c0b-1e17197e0cf7.mp4

### Version

Latest dev branch, but it was happening before

### Frigate config file

```yaml
snapshots:
  enabled: true
cameras:
  video_porteiro:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/video_porteiro?video=copy
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/video_porteiro_hd
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      width: 1280
      height: 720
    live:
      height: 720
    zones:
      video_porteiro_area:
        coordinates: 956,720,835,617,724,617,512,720
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua VTO2202F-P-S2

**Comment by NickM-27** [comment] 2023-02-20 15:01
Frigate 0.12 has no memory and will not set based on MQTT retained values. So if this is happening on reboot it is due to an automation or something running on frigate startup. I'd suggest enabling mqtt debug logs, restart frigate, and see where the topic is being set

**Comment by felipecrs** [comment] 2023-02-20 15:03
Documentation does not mention how to enable mqtt logs, is it like following:

```
logger:
  default: info
  logs:
    mqtt: debug
```

**Comment by felipecrs** [comment] 2023-02-20 15:04
Ops my bad, it actually mentions here:

https://deploy-preview-4055--frigate-docs.netlify.app/configuration/advanced

I was looking at the full config file.

**Comment by NickM-27** [comment] 2023-02-20 15:05
Sorry I meant logs on your mqtt broker, but frigate mqtt logs will probably hold the same data

**Comment by NickM-27** [comment] 2023-02-20 15:13
That's odd, we would expect that to be cleared on startup automatically

https://github.com/blakeblackshear/frigate/blob/a8c567d877e9874312cf1cb525da6cfa717b0a04/frigate/comms/mqtt.py#L160-L164

**Comment by felipecrs** [comment] 2023-02-20 15:35
Maybe that's a small bug then... Well, I'd recommend not spending time on it unless someone else complains.

**Comment by Henk72** [comment] 2023-05-03 09:53
I have the same issue, Frigate disables the recording and snapshot, even tough I enabled them in the config. I think it is indeed in my case MQTT related.

**Comment by fliespl** [comment] 2023-05-09 20:15
Having same issue with reolink camera:

```2023-05-09 20:09:39.254870521  [2023-05-09 20:09:39] frigate.app                    INFO    : Camera processor started for reolink: 694
2023-05-09 20:09:39.259394676  [2023-05-09 20:09:39] frigate.app                    INFO    : Camera processor started for eufy1: 695
2023-05-09 20:09:39.264027776  [2023-05-09 20:09:39] frigate.app                    INFO    : Camera processor started for eufy2: 696
2023-05-09 20:09:39.280436919  [2023-05-09 20:09:39] frigate.app                    INFO    : Camera processor started for eufy3: 698
2023-05-09 20:09:39.280786056  [2023-05-09 20:09:39] frigate.app                    INFO    : Capture process started for reolink: 699
2023-05-09 20:09:39.280989158  [2023-05-09 20:09:39] frigate.app                    INFO    : Capture process started for eufy1: 702
2023-05-09 20:09:39.281171250  [2023-05-09 20:09:39] frigate.app                    INFO    : Capture process started for eufy2: 706
2023-05-09 20:09:39.285632917  [2023-05-09 20:09:39] frigate.app                    INFO    : Capture process started for eufy3: 709
...
2023-05-09 20:09:39.301448665  [2023-05-09 20:09:39] frigate.comms.dispatcher       INFO    : Turning on snapshots for eufy1
2023-05-09 20:09:39.302145637  [2023-05-09 20:09:39] frigate.comms.dispatcher       INFO    : Turning on snapshots for eufy2
2023-05-09 20:09:39.303604270  [2023-05-09 20:09:39] frigate.comms.dispatcher       INFO    : Turning on snapshots for eufy3
```

**Comment by Burkey2k** [comment] 2023-07-12 23:26
I have this same issue also, and deleting the topic in MQTT has no effect (have deleted all retains I could find).

**Comment by felipecrs** [comment] 2023-07-12 23:29
I'm reopening my own issue, following my own comment:

> Maybe that's a small bug then... Well, I'd recommend not spending time on it unless someone else complains.

**Comment by Burkey2k** [comment] 2023-07-12 23:32
For clarity, I have two Tapo cameras, and it only affects one of them. Exact same behaviour as described above otherwise. I will have more time to investigate on MQTT explorer this weekend, but after a few hours of going through logs and troubleshooting last night, I'm at a loss (but I'm in no way am expert!).

**Comment by eloquentvogon** [comment] 2023-07-20 20:14
I have noticed on my wyze and foscam that snapshots are also disabled after restart

**Comment by monkmad** [comment] 2023-07-25 14:03
I have the same issue. My setup has 5 Reolink cameras and one other. On startup, it always defaults to snapshots disabled for three cameras and I have to toggle it On in the UI. Setting snapshots to enabled in the config (under each camera --> mqtt) has no effect. I'm on the latest stable version.

**Comment by NickM-27** [comment] 2023-07-25 14:04
> Setting snapshots to enabled in the config (under each camera --> mqtt) has no effect

That's the wrong place in the config that you would enable snapshots, so seems like that would be the issue

**Comment by NickM-27** [comment] 2023-07-25 14:42
I don't see snapshots -> enabled in your example, that is the only part that would matter.

**Comment by monkmad** [comment] 2023-07-25 14:48
Ah! For some reason, I mistakenly thought the default value was True. Setting it explicitly to true fixed all the cameras. D'oh! 🤦
Thanks!

**Comment by NickM-27** [comment] 2023-07-25 14:49
I am going to close this, users experiencing this issue should create their own separate issue and provide the config file, logs, etc. so it will be immediately obvious what the problem is.

**Closed by NickM-27** 2023-07-25 14:49 UTC
Labels: support, triage, beta

**Comment by PeggyFree** [comment] 2024-09-21 15:41
> Hm, deleting this topic in MQTT fixed the issue:
> MQTT_Explorer_fyMJ8KBXgy.mp4
> 
> Thanks!

This topic deletion also solved the issue in my config, thanks for the detailed answer !
