### ISSUE TITLE
[REQ] Toggle camera Capture

### ISSUE THREAD

**Issue by lordraiden** [blakeblackshear/frigate#7039] opened 2023-07-05 16:00 UTC
I would like an option to toggle camera capture in frigate and have it available via Home Assistant as well.
Why?
Imagine that I have 20 cameras or cameras that I want to have configured to consume them on demand o based on an automation, right now these cameras consume CPU for doing nothing.
So in the same way I can disable detection, recording, snapshots... an option to disable capture would be nice

![imagen](https://github.com/blakeblackshear/frigate/assets/17175395/de50de7c-1ead-494b-8fad-6581861cdb5a)

![imagen](https://github.com/blakeblackshear/frigate/assets/17175395/1fbdabf4-ca42-4f35-a760-c75304a878ab)

**Comment by NickM-27** [comment] 2023-07-05 16:02
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1911

**Closed by NickM-27** 2023-07-05 16:02 UTC
Labels: duplicate, enhancement

**Comment by lordraiden** [comment] 2023-07-06 14:15
and it is possible to configure frigate to have certain toggles disable by default on boot but still configured?

**Comment by NickM-27** [comment] 2023-07-06 14:29
> and it is possible to configure frigate to have certain toggles disable by default on boot but still configured?

no, you need to use an automation to do this currently; it used to be possible but there were too many issues with stuck and confusing states
