### ISSUE TITLE
Add user management / need rights to delete

### ISSUE THREAD

**Issue by jmtatsch** [blakeblackshear/frigate#10880] opened 2024-04-08 06:16 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to show a live view for everyone, but only certain people should be able to review footage and even less people should be able to delete footage.

**Describe the solution you'd like**
Introduce a minimal user/role management with the following roles:
* everyone: can watch live view
* user: can review historic footage, maybe review events
* admin: can change config, can add users, delete footage

**Describe alternatives you've considered**
Could use nginx to expose certain paths of frigate to different groups but this would become a giant mess soon.

**Additional context**
I think this is frequently needed in professional surveillance system settings.
Unifi has this https://help.ui.com/hc/en-us/articles/1500011491541-Granting-Access-to-UniFi-Roles-and-Permissions
the per camera settings I would say are a bit too fine grained...

**Comment by NickM-27** [comment] 2024-04-08 12:33
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/6614, feel free to leave 👍 and any extra details there

**Closed by NickM-27** 2024-04-08 12:33 UTC
Labels: duplicate, enhancement
