### ISSUE TITLE
Feature request: Debug view for video clips / previous events

### ISSUE THREAD

**Issue by stephen322** [blakeblackshear/frigate#2907] opened 2022-03-06 18:56 UTC
It would be nice to be able to run the debug view on recorded clips to better see what's happening (false positives and false negatives) and to help with zone setup.

**Describe the solution you'd like**
A debug button available on each event, that would show the same interface as Debug tab on the live view complete with options for motion, bounding box, zones, etc.
And ideally, an upload button on the debug page for a user-provided video file, for events that were not tracked properly.

**Comment by blakeblackshear** [comment] 2022-03-10 11:58
Duplicate of #1914

**Closed by blakeblackshear** 2022-03-10 11:58 UTC
Labels: enhancement
