### ISSUE TITLE
Multiple Birdseye instance

### ISSUE THREAD

**Issue by setterlee** [blakeblackshear/frigate#4755] opened 2022-12-20 13:41 UTC
**Describe what you are trying to accomplish and why in non technical terms**
Would be nice to have the availabilty to define multiple instances of birdseye with different configurations.  

**Describe the solution you'd like**
Change the property type of birdseye to array and see multiple birdseye instances at the front page

**Describe alternatives you've considered**
nothing here, maybe a cronjob in my server to swap between two configuration files at nights

**Additional context**
At day I like to have the birdseyes in motion mode in my office and I was thinking that I need to have the birdseye in detection motion on the tv on my bedroom to keep an eye in mi house at nights.

**Comment by NickM-27** [comment] 2022-12-20 13:51
Based on the context it sounds less like a need for multiple birdseye and more like a need to change birdseye mode via an api / home assistant automation?

**Comment by setterlee** [comment] 2022-12-20 13:52
yep, that could be work...

**Comment by NickM-27** [comment] 2022-12-20 13:56
I'm going to tag this as a duplicate of https://github.com/blakeblackshear/frigate/issues/3244

I have a draft of this feature as well. Feel free to leave any additional thoughts on the linked issue

**Comment by setterlee** [comment] 2022-12-20 13:57
ok ok Thanks @NickM-27

**Closed** 2022-12-20 13:57 UTC
Labels: duplicate, enhancement
