### ISSUE TITLE
[Support]: Mask & Zone Creator, disable Snap to Edges option not working

### ISSUE THREAD

**Issue by baylanger** [blakeblackshear/frigate#9088] opened 2023-12-27 16:09 UTC
### Describe the problem you are having

Hi.

I searched in the docs, discussions ad open/close issues, couldn't find any info on this topic.

Regardless if "snap to edges" is enable or not, the Mask & Zone Creator UI still snaps points to edges. Correct me if I'm wrong, disabling this option should allow the end user to freely place a point. If so, that's not the case. With this option disable, all points still want to snap and don't freely move.

### Version

0.12.0 & 0.13-beta7

### Frigate config file

```yaml
# Providing bare minimum config just in case the root cause could be related to camera resolution?

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
    frontyard:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@12.16.8.XXX:554/Streaming/Channels/101
    frontyard_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@12.16.8.XXX:554/Streaming/Channels/102

cameras:
  frontyard:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://localhost:8554/frontyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://localhost:8554/frontyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      # use same resolution as feed
      width: 1280
      height: 720
      fps: 12
```

### Relevant log output

```shell
Not needed.
```

### FFprobe output from your camera

```shell
Not needed.
```

### Frigate stats

```json
Not needed.
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

Same behavior in Chrome 118.0.5993.70 & Firefox 121.0

**Comment by baylanger** [comment] 2023-12-30 03:48
Just tested with 0.13-beta7 - again getting the same behavior with the option enable or disable. It tries to snap all the time.

**Comment by NickM-27** [comment] 2023-12-30 03:50
What browser are you using? I've never had an issue freely moving a point of the mask

**Comment by baylanger** [comment] 2023-12-30 03:58
Right here, both are the latest version.

```
Any other information that may be helpful
Same behavior in Chrome 118.0.5993.70 & Firefox 121.0
```

**Comment by baylanger** [comment] 2023-12-30 04:04
FYI just edited last comment to add a video.

Could it be the high-res video that makes the dot jumping around?

**Comment by nwish** [comment] 2023-12-30 04:29
I could be wrong, but I thought “snap to edges” causes the points to… well, snap to the edges of the frame.  I think what you’re experiencing is normal.

**Comment by baylanger** [comment] 2023-12-30 04:39
The issue is that "snap to edges" option is disable but the dot appears to still snap. With the option on or off, the dot moves the same way.

**Comment by nwish** [comment] 2023-12-30 21:19
> The issue is that "snap to edges" option is disable but the dot appears to still snap. With the option on or off, the dot moves the same way.

Right.  What I'm saying is that I believe that option only controls how the points behave when moved close to the edge of the frame, not how they move in general.  To see for yourself, turn it off and try to move a point as close to the edge of the frame as you can.  You'll see you can get it pretty close, but still not touching.  Now turn the setting on and do the same, and you should notice the point "snapping" straight to the edge.  

I don't really see a benefit to this option either way, as you can still drag the dot all the way to the edge with the setting off.

**Comment by NickM-27** [comment] 2023-12-30 21:31
yeah, I misunderstood what OP was talking about, that video shows things working as expected (regardless of the snap to edges option)

closing this as working as intended

**Closed by NickM-27** 2023-12-30 21:31 UTC
Labels: support, triage

**Comment by baylanger** [comment] 2024-01-01 21:21
And I misunderstood how the Snap/Edges option works. I had 2 classes of infographic, years ago and one lab was detect lines. With Snap to Edges enable, I thought when moving the cursor that it would look for edges.. like the garage's entrance edges with the grass, the edge of the garage entrance with the sidewalk, etc.

I still wish it would be possible to precisely drop a dot, with a few tests on the X/Y axis it jumps ~12-13 pixels instead of 1 pixel at a time. For some zones, it still works fine but for others I need to make compromises.

**Comment by nwish** [comment] 2024-01-01 22:12
> I still wish it would be possible to precisely drop a dot, with a few tests on the X/Y axis it jumps ~12-13 pixels instead of 1 pixel at a time. For some zones, it still works fine but for others I need to make compromises.

I do agree with you about that.
