### ISSUE TITLE
Auto labeled on frigate+ upload

### ISSUE THREAD

**Issue by mabed-fr** [blakeblackshear/frigate#9359] opened 2024-01-16 19:02 UTC
Hello,

member of the frigate community for 1 month and member of frigate+ for a few weeks as well as obtaining my first personalized model with more than 600 labels, I notice that with each upload (false or true upload) I have to label with frigate is able to recognize for me (car, dog, cat, license plate, etc.) is it not possible to label check upload to frigate+ with multiple boxes to limit the validation time on frigate+?

**Comment by NickM-27** [comment] 2024-01-16 19:03
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/8229

**Closed by NickM-27** 2024-01-16 19:03 UTC
Labels: duplicate, enhancement
