### ISSUE TITLE
Birdseye: Manual trigger a specific camera (API or MQTT)

### ISSUE THREAD

**Issue by sberryman** [blakeblackshear/frigate#8207] opened 2023-10-17 18:51 UTC
I would like to be able to trigger a specific camera to be included in Birdseye based on a home assistant automation. My use case is when my backyard door is open or unlocked I would like to ensure that camera is always visible until closed/locked.

Essentially I would like the ability to change camera(s) birdseye mode between `continuous` and `object` via an automation in home assistant.
```yaml
camera:
  backyard_door:
    birdseye:
      mode: {value}
```

I would expect a topic similar to:
```
frigate/<camera_name>/birdseye/mode/set
```

Is this something anyone else has run into or would considering adding to 0.13?

**Comment by NickM-27** [comment] 2023-10-17 18:53
Closing this as it is a duplicate of https://github.com/blakeblackshear/frigate/issues/3244

feel free to leave a 👍  and any additional thoughts

**Closed by NickM-27** 2023-10-17 18:53 UTC
Labels: duplicate, enhancement
