### ISSUE TITLE
Feature Request: Timeline/"Nest-like" or "Homekit-like" scrubbing view

### ISSUE THREAD

**Issue by jkmaxwell** [blakeblackshear/frigate#1390] opened 2021-07-15 20:42 UTC
**Describe the bug**
When I am browsing events I like to see them in a scrubbable historical view so I can see context. Clips are a 1 by 1 procedure.

**Version of frigate**
N/A

**Config file**
N/A

**Frigate container logs**
N/A

**Frigate stats**
N/A

**FFprobe from your camera**
N/A

**Screenshots**
https://imgur.com/a/xHEupOU

**Comment by blakeblackshear** [comment] 2021-07-16 12:53
It's not quite as nice as the UI for Nest, but here is what is coming in the next version: https://github.com/blakeblackshear/frigate/pull/1155#issuecomment-854948555

**Comment by stcbus** [comment] 2022-01-26 15:11
I would love to see this as well.

**Comment by NickM-27** [comment] 2023-03-20 23:18
Closing this as a duplicate of https://github.com/blakeblackshear/frigate/issues/2230

typically the newer issue would get closed but in this case https://github.com/blakeblackshear/frigate/issues/2230 has much more discussion / ideas so this one is closed 👍

**Closed by NickM-27** 2023-03-20 23:18 UTC
Labels: duplicate
