### ISSUE TITLE
Beeing able to use the send to Frigate + button for manually created snapshot

### ISSUE THREAD

**Issue by xavan83** [blakeblackshear/frigate#10122] opened 2024-02-28 09:49 UTC
I want to be able to take snapshots at regular interval and be able to send them to Frigate+
I create snapshot using the "/api/events/cameraname/label/create"
The resulting snapshot can not be uploaded to Frigate+, the button is disabled
I had to save the snapshot locally and upload it manually through the Frigate+ web page

**Comment by NickM-27** [comment] 2024-02-28 14:01
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/8038

**Closed by NickM-27** 2024-02-28 14:01 UTC
Labels: duplicate, enhancement
