### ISSUE TITLE
Trigger clip recording from a Home Assistant event

### ISSUE THREAD

**Issue by OldGreyCells** [blakeblackshear/frigate#2182] opened 2021-11-04 18:15 UTC
I'd like to be able to trigger the recording of an event from Home Assistant - e.g. when a PIR is triggered one or more cameras start recording for a period of time.

It could be via MQTT or directly from a HA event.

I have not found a way of doing this in the documentation, so have tagged this as an enhancement request.

**Comment by blakeblackshear** [comment] 2021-11-04 19:21
Duplicate of #1063

**Closed by blakeblackshear** 2021-11-04 19:21 UTC
Labels: enhancement
