### ISSUE TITLE
zoom in playback slider

### ISSUE THREAD

**Issue by belmont** [blakeblackshear/frigate#15677] opened 2024-12-25 10:12 UTC
I am testing the latest v15 beta version (0.15.0-87e7b62)  and would like to suggest an enhancement. When users want to replay a segment, they move the timeline on the right side, but it can be challenging to pinpoint specific moments, such as when a car or bicycle appears for just a few frames. Could you consider adding zoom functionality to the slider? This would make it easier to navigate and locate the exact frame where an object is most visible. Overall, the latest beta seems quite good. As others have suggested, supporting local AI – Ollama would also be a great addition.

**Comment by NickM-27** [comment] 2024-12-25 12:47
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/11398

**Closed** 2024-12-25 12:47 UTC
Labels: duplicate, enhancement
