### ISSUE TITLE
[Support]: Screen is shaking around specific resolution

### ISSUE THREAD

**Issue by Mincka** [blakeblackshear/frigate#2073] opened 2021-10-21 19:56 UTC
### Describe the problem you are having

The screen is shaking when my Edge browser is in full screen with favorite bar on Windows 11. 
This issue can be also reproduced using Firefox.

![Animation](https://user-images.githubusercontent.com/6184289/138347067-e824bb64-b97e-4d50-b6b0-144ad04a1a54.gif)
(The shaking is a lot faster in reality)

The resolution is:
![image](https://user-images.githubusercontent.com/6184289/138347241-b21fa8ee-a9e9-466a-a77a-74c42398b698.png)

But it does not have to be specifically this resolution, it's around this height.

### Version

0.9.1

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2186G2-I

**Comment by blakeblackshear** [comment] 2021-11-02 11:26
Duplicate of #1657

**Closed by blakeblackshear** 2021-11-02 11:26 UTC
Labels: bug, frontend, pinned
