### ISSUE TITLE
Would love to see some better navigation for recording / events like Day / Night & Clip Length.

### ISSUE THREAD

**Issue by dopeytree** [blakeblackshear/frigate#7881] opened 2023-09-19 19:00 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 

Would love to see some better navigation for recording / events like Day / Night & Clip Length / File Size

**Describe the solution you'd like**

5 🐈     1 🐕    30 🚗     15🧍     ---    ☀️    ---     [ 0 - 1m ]   ---   ⬇

So maybe a bar with the above icons showing on the video gallery & events page

**Describe alternatives you've considered**

This is mostly to help while tuning the system. I have some long car recordings I want to delete but also it's just cool to tap a moon symbol and see all the night recordings.

Also a quick summary of the objects counted per day would be super cool as it's already there in the database.

☀️🌛 - Filters: Day / Night / Off - shows day or night recordings

[ 0 - 1m ] - drop down selector - shows clips according to length
1m - 5m
5m - 30m
30m - 1h
1h+
Any

5 🐈 - simple object tally per day (or selecting time frame) with emoji or just the world for the object
1 🐕
30 🚗
15 🧍

⬇ - Alternating icon: File size: Ascending / Descending / Off -  depending on which is active - shows clips by file size
⬆

**Additional context**

**Comment by NickM-27** [comment] 2023-09-19 19:01
This is a very open ended and ambiguous feature request, I would suggest separate issues for each feature request. Also worth noting some of these already have open and pinned feature request issues

**Comment by dopeytree** [comment] 2023-09-19 19:08
file size would be the most useful. I tried to go manually through the folders but each day is split into hours so a bit of folder caption. trying to delete those 8hour recordings on my car 😅

**Comment by NickM-27** [comment] 2023-09-19 19:12
that's not really how recordings work, they are saved in segments and any given recording segment can be used for the playback of multiple events. So the size of all recording segments added up for that single event could be shown but you'd likely be surprised when not that much storage is cleaned up when you delete the event

**Comment by dopeytree** [comment] 2023-09-19 19:18
Ah ok well how do I investigate a sudden increase in storage use.. It was under 50GB. 

The camera uses 415MB/hr x2 then 1x 2.2GB/hr both are set to record only detected objects & keep for 7 days.

Am about to add 5x more of the 2.2GB/hr cameras.

**Comment by NickM-27** [comment] 2023-09-19 19:21
sounds like this should be closed and a support issue should be opened

**Comment by NickM-27** [comment] 2023-09-19 19:55
closing as duplicate of new requests that have been created

**Closed by NickM-27** 2023-09-19 19:55 UTC
Labels: enhancement
