### ISSUE TITLE
Collapsable Side Menu

### ISSUE THREAD

**Issue by crashnbernstein** [blakeblackshear/frigate#5526] opened 2023-02-17 13:17 UTC
I Love frigate. Best thing since sliced bread.

What might make it even better is to have the side menu on the web page collapsible. A toggle arrow that can either show or hide the side menu. Lots of screen space could be gained by collapsing it. I use the navigation on the side panel very rarely, opting instead to have 2 or three windows open to view the various live feeds. I could squeeze in another window, if the menu was collapsible. 

Thanks for all the hard work and great program. I'm in the software arena, and I can tell you that even some highly paid projects the develop software come no where near what you have provided for FREE. 

Cheers,
Crashn

**Comment by NickM-27** [comment] 2023-02-17 13:23
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/2617

**Closed by NickM-27** 2023-02-17 13:23 UTC
Labels: duplicate, enhancement

**Comment by crashnbernstein** [comment] 2023-02-17 13:39
Thanks. Any idea when it might make the roadmap, or be considered for development?

**Comment by NickM-27** [comment] 2023-02-17 13:42
> Thanks. Any idea when it might make the roadmap, or be considered for development?

it's pinned so it will be done at some point. There's over 100 pinned feature requests so lots to be done

**Comment by NickM-27** [comment] 2023-02-17 13:42
We are always happy to accept contributions as well

**Comment by crashnbernstein** [comment] 2023-02-17 13:49
By contribution do you mean donation, or develop the enhancement and submit for consideration?  Happy to do the first, the second, not sure i'm qualified. I took a peek inside the frigate console at the web folder, but i'm not following how its constructed. I know enough about web development to be dangerous, and even less about JS which seems to be used quite extensively.

**Comment by NickM-27** [comment] 2023-02-17 13:50
> develop the enhancement and submit for consideration? 

that's what I meant 👍 all good if not just figured I would mention it

**Comment by crashnbernstein** [comment] 2023-02-17 14:07
I will give it a try. Always willing to learn something new, and
contributing to the teams FANTASTIC project will be rewarding
