### ISSUE TITLE
Exclude Area/Mask from recording

### ISSUE THREAD

**Issue by bjwo** [blakeblackshear/frigate#5625] opened 2023-03-02 11:04 UTC
**Describe what you are trying to accomplish and why in non technical terms**
In some regions (e.g. Germany) you are not allowed to record any public areas outside your property due to data privacy laws. In some cases, there might not be a good position how you can place the camera without recording public areas. I would like to be able to exclude / blackout these areas from my recording.

**Describe the solution you'd like**
I would like to be able to define an area using a mask. This area should be blacked out in the recorded videos.

**Comment by NickM-27** [comment] 2023-03-02 13:41
This is a duplicate of #4722

I'd recommend looking at https://github.com/blakeblackshear/frigate/discussions/2866

This is a very CPU intensive task so you'd really want to do this on your camera directly. 

If your camera does not support this then frigate already supports this using ffmpeg output args

**Closed by NickM-27** 2023-03-02 13:41 UTC
Labels: duplicate, enhancement
