### ISSUE TITLE
Support for CUDA

### ISSUE THREAD

**Issue by weitheng** [blakeblackshear/frigate#1210] opened 2021-06-12 08:02 UTC
Are there any plans to include CUDA? Currently running on a Jetson Nano, it will be great if it includes CUDA support.

**Comment by eldadh** [comment] 2021-06-12 09:10
From What i see, there is either aarch64 or Nvidia base on amd64.
it would be great to merge them for jetson product line

**Comment by chrisevans1001** [comment] 2021-07-11 20:25
Duplicate of #659

**Closed** 2021-07-13 10:36 UTC
