### ISSUE TITLE
MQTT topic for active objects

### ISSUE THREAD

**Issue by vacumet** [blakeblackshear/frigate#9670] opened 2024-02-05 12:52 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I use frigate to detect active objects and with Node-RED i trigger actions in home assistant. Before the latest update stationary objects stoped counting. Now i can's see a way to differentiate active and stationary objects via MQTT

**Describe the solution you'd like**
I wish there was MQTT topics for active objects like:
frigate/+/active/car
frigate/+/active/all

Maybe stationary would be interesting to have too for some scenarios:
frigate/+/stationary/car
frigate/+/stationary/all

**Describe alternatives you've considered**
Right now i stay at 0.12.1 as stationary objects stops counting but it doesn't work in the long run.

**Additional context**

**Comment by NickM-27** [comment] 2024-02-05 12:53
to be clear this behavior did not change from 0.12 to. 0.13, stationary objects have always counted towards the count if they were tracked and considered a true positive. 

this is a duplicate of https://github.com/blakeblackshear/frigate/issues/7667

**Closed by NickM-27** 2024-02-05 12:53 UTC
Labels: duplicate, enhancement
