### ISSUE TITLE
Post process events

### ISSUE THREAD

**Issue by ctml91** [blakeblackshear/frigate#8577] opened 2023-11-10 22:11 UTC
**Describe what you are trying to accomplish and why in non technical terms**
For machines with lack of resources, it might be helpful to have an option to post process events, specifically recordings instead of having ffmpeg constantly doing things like (for example) rotating a feed. So for an event that created a recording, after it's complete run some post processing on it with ffmpeg flags to handle things like rotation.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Upgrading HW to be more powerful.  

**Additional context**
I'm not sure how this would affect things like mqtt/home assistant. Ideally if something like this were possible home assistant/mqtt either receives the updated version post processing or its held until completed. Particularly important for notifications.

**Comment by NickM-27** [comment] 2023-11-10 22:14
I am going to close this as a duplicate of https://github.com/blakeblackshear/frigate/issues/2243#issuecomment-968101551 which describes a similar usecase

**Closed by NickM-27** 2023-11-10 22:14 UTC
Labels: duplicate, enhancement
