### ISSUE TITLE
Allow automations to modify config via mqtt or api?

### ISSUE THREAD

**Issue by r3wt** [blakeblackshear/frigate#7986] opened 2023-09-29 01:07 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to enable/disable a camera using a toggle switch on the UI. in particular, so i can add a living room camera to monitor the dogs and cat while i'm at work, but also when we're on the porch swing, its creepy having the doorbell record us. 
**Describe the solution you'd like**
Ability to send commands from HA automations via MQTT or api

**Describe alternatives you've considered**
i could put the poe switch on a z wave smart plug and cut all the cameras by that method, but its not as cool or as useful.

**Additional context**

I'm willing to submit a PR for the feature. but first i wanted to gauge your interest in even supporting such a feature, discuss the scope of the requirements etc. 

Thanks

**Comment by NickM-27** [comment] 2023-09-29 01:20
The API for editing the config file already exists. 

There's also already a pinned issue for what you suggest, editing the config file and restarting frigate is not a viable solution for this usecase #1911

https://github.com/blakeblackshear/frigate/pull/6744 was an in progress implementation but it had issues that I outlined and the author has chosen to not continue working on it 

Seeing as the ability to edit the config already exists via API and the use case for your request is already duplicate of an existing issue, I'm closing this as a duplicate.

**Closed** 2023-09-29 01:20 UTC
Labels: duplicate, enhancement
