### ISSUE TITLE
Proper export function

### ISSUE THREAD

**Issue by user897943** [blakeblackshear/frigate#5631] opened 2023-03-03 03:24 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 

Will try being brief, I can get wordy...

I want to be able to open my cam, and export a specific section by saying "start from date/time PP/PP/PPPP KK:KK until NN/NN/NNNN TT:TT and Frigate will spit out a file for me to download (or it sends to the download queue of my browser automatically upon clicking "export".

Example:

Camera 1 > Recordings > Export (button) > Select IN date/time (for example 8/25/2022 15:33:04 (dropdown menus or a timeline just like the Nest camera website), select OUT date/time (for example 8/27/2022 08:23:22 > click, Export footage...

Frigate will get all segments between August 25th 2022 starting 3:33:04PM and August 27th 2022 at 8:23:22AM, merge them, create a single video with timestamps optional, and let me download that.

WHY?

Because now to export video for the police or neighbors I have to browse to my storage using NFS, copy each segment manually, and use something like Shutter Encoder to manually piece everything together hoping the sequence will be correct, then wait for Shutter Encoder to merge all segments, then I have to delete all the "temp" data I copied. It's just too much work when Frigate already has all the segments and can easily do it.

**Comment by user897943** [comment] 2023-03-03 03:28
How quick do I want this? YESTERDAY. Why? Because any NVR you find on the market right now already has an export function so it boggles my mind why this one doesn't. It's a basic feature. No criticism here at all, and no personal attack meant by this, I love Frigate and love the innovative approach but please don't focus on doing fancy obj det in favor of things that should be basic from the start. We had to wait until 0.12 for basic storage management for Christ's sake... Please focus on giving features that are considered essential for any NVR first. Easy exporting is absolutely an essential for a security system. Without exporting data in the correct sequence the evidence is as good as a flaming bag of crap in court. Pardon my language but I wanna be direct about it. Thanks.

**Comment by user897943** [comment] 2023-03-03 03:29
Oh and I am totally aware that this is someone else's time and effort and that I could do it myself. I would if I knew how. Not a demand by any means, only saying it's something I believe most users would agree is important to have when using a security recorder.

**Comment by NickM-27** [comment] 2023-03-03 03:37
Thanks for the request, this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2369

As it says in that issue, the feature already exists there is just no ui for it. Using ffmpeg and the frigate API this is relatively easy to do to create one long file. The value of the UI is recognized and that is why the feature is pinned. 

Feel free to leave your thoughts on that issue.

**Closed** 2023-03-03 03:38 UTC
Labels: duplicate, enhancement
