### ISSUE TITLE
Birdsview fullscreen URL

### ISSUE THREAD

**Issue by martinjung7109** [blakeblackshear/frigate#6534] opened 2023-05-18 22:21 UTC
I want to configure Microsoft Edge in kiosk mode on a Windows machine to display the Birdsview feed on a screen. 
It's already possible to view the stream in fullscreen by clicking or tapping on it but I'd need a dedicated URL to directly open Birdsview in fullscreen.

**Comment by NickM-27** [comment] 2023-05-18 22:47
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1891

**Closed by NickM-27** 2023-05-18 22:47 UTC
Labels: duplicate, enhancement
