### ISSUE TITLE
[Feature Request] Pre-populate bounding boxes for attribute labels (face, license plate, etc) in Frigate+ for submitted images

### ISSUE THREAD

**Issue by dimatx** [blakeblackshear/frigate#9104] opened 2023-12-28 19:16 UTC
**Describe what you are trying to accomplish and why in non technical terms**
Currently (v13b7), when a Frigate+ model (correctly) detects a person and a face (or a car and a license plate), when it is submitted to Frigate+, the only bounding box shown is the person or a car, requiring user to add the attribute labels even if they were already correctly identified by the model.

**Describe the solution you'd like**
Show all labels for an image in the submission, including attribute labels.

**Describe alternatives you've considered**
The alternative is that the user has to make sure they apply those attributes labels in the images in Frigate+ UI, instead of just confirming that everything was correctly identified by the model.

**Comment by NickM-27** [comment] 2023-12-28 19:30
Closing this as a duplicate of https://github.com/blakeblackshear/frigate/issues/8229

**Closed by NickM-27** 2023-12-28 19:30 UTC
Labels: duplicate, enhancement
