### ISSUE TITLE
  user conditions camera

### ISSUE THREAD

**Issue by niro-zz** [blakeblackshear/frigate#15038] opened 2024-11-17 17:30 UTC
hi hello Is it possible to hide a camera from a user? for example I have two users and 4 cameras I want user 1 to be able to access all of them And an additional user only for 2 cameras And also to hide the recordings and all other related things

**Comment by NickM-27** [comment] 2024-11-17 17:32
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/6614

**Closed by NickM-27** 2024-11-17 17:32 UTC
Labels: duplicate, enhancement
