### ISSUE TITLE
Add Select ALL checkboxes mass select for delete in Events.

### ISSUE THREAD

**Issue by superdong69** [blakeblackshear/frigate#8087] opened 2023-10-07 12:49 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to either select all to delete events, or shift select from the one to the next and select a range of events to delete in mass. Example. You have a party, and have 1000 events you want to delete in mass on multiple cameras. Spamming the trash icon took me forever.

**Describe the solution you'd like**
To have a checkbox field on the left outer most column of events view, with a checkbox in the header for "Select ALL". One should be able to check and select a couple, all at once using the select all box in the header( say if you sort for last 24 hours, you could delete just all the last 24 hours by clicking select all in that filter view) or check one box, hold down SHIFT, click one further down, and it would select all those inbetween. Similar to how Gmail handles this,

**Describe alternatives you've considered**
Haven't thought of any.

**Additional context**

**Comment by NickM-27** [comment] 2023-10-07 13:04
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/2063 and https://github.com/blakeblackshear/frigate/issues/2223

**Closed** 2023-10-07 13:04 UTC
Labels: duplicate, enhancement
