### ISSUE TITLE
Disable Motion Detection via Config

### ISSUE THREAD

**Issue by jangrewe** [blakeblackshear/frigate#9064] opened 2023-12-23 16:21 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to disable the motion detection state via the config, just like the (object) detection, so that restarting Frigate doesn't start with motion detection enabled.

The reason is that i use MQTT to toggle the surveillance in my home, and i can do that via the MQTT topic `frigate/<camera_name>/motion/set` (thanks to https://github.com/jgow/org.openhab.binding.mqtt.frigatesvr in openHAB), but i need to manually disable the motion detection that way every time Frigate is restarted.

**Describe the solution you'd like**
```
motion:
  enabled: False
```

**Describe alternatives you've considered**
Disabling the cameras completely on startup, but that's unsatisfactory, as i can't view them then unless motion detection is enabled.

**Additional context**

**Comment by NickM-27** [comment] 2023-12-23 16:26
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/4326

Feel free to add comment and 👍 on the issue to show support

**Comment by jangrewe** [comment] 2023-12-23 16:27
Oh, i searched the issues, but didn't see that one before... thanks!

**Closed by NickM-27** 2023-12-23 16:26 UTC
Labels: duplicate, enhancement
