### ISSUE TITLE
CPU usage high even if everything is turned off

### ISSUE THREAD

**Issue by runningman84** [blakeblackshear/frigate#2162] opened 2021-11-01 11:14 UTC
### Describe the problem you are having

I have a simple setup using a single unifi full hd camera.

The detection works fine.

Frigate needs about 0.5 cpu cores and 650 mb ram of my intel n5000 system.

From my point of view the cpu load should go to zero once I switch of detection, recordings and snapshots for my single camera. But the load stays high.

It looks like the load is high because the ffmpeg process is not stopped here... 

My idea is to run frigate only if the alarm system is armed.

### Version

0.9.4

### Frigate config file

```yaml
mqtt:
  host: mosquitto
  topic_prefix: frigate
  # user: ${SECRET_MQTT_USERNAME}
  # password: ${SECRET_MQTT_PASSWORD}
database:
  path: /data/frigate.db
detectors:
  coral:
    type: edgetpu
    device: pci:0
# Global objects configuration
objects:
  track:
    - person
  filters:
    person:
      min_area: 2500
      max_area: 100000
      threshold: 0.7
# Global ffmpeg configuration
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
 # Specify camera's
cameras:
  # --
  corridor_downstairs:
    ffmpeg:
      inputs:
        - path: rtsp://xx.xx.xx.xx:554/s0
          roles:
            - detect
        - path: rtsp://xx.xx.xx.xx:554/s0
          roles:
            - rtmp
            - record
    rtmp:
      enabled: True
    detect:
      # width: 960
      # height: 720
      fps: 5
    record:
      enabled: True
      retain_days: 0
      events:
        retain:
          default: 14
    snapshots:
      enabled: True
      timestamp: False
      retain:
        default: 14
    objects:
      track:
        - person
```

### Relevant log output

```shell
Container output:

│ [s6-init] making user provided files available at /var/run/s6/etc...exited 0.                                                                          │
│ [s6-init] ensuring user provided files have correct perms...exited 0.                                                                                  │
│ [fix-attrs.d] applying ownership & permissions fixes...                                                                                                │
│ [fix-attrs.d] done.                                                                                                                                    │
│ [cont-init.d] executing container initialization scripts...                                                                                            │
│ [cont-init.d] done.                                                                                                                                    │
│ [services.d] starting services                                                                                                                         │
│ [services.d] done.                                                                                                                                     │
│ [2021-10-31 22:29:14] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)                                                        │
│ [2021-10-31 22:29:14] frigate.app                    INFO    : Creating directory: /tmp/cache                                                          │
│ Starting migrations                                                                                                                                    │
│ [2021-10-31 22:29:14] peewee_migrate                 INFO    : Starting migrations                                                                     │
│ There is nothing to migrate                                                                                                                            │
│ [2021-10-31 22:29:14] peewee_migrate                 INFO    : There is nothing to migrate                                                             │
│ [2021-10-31 22:29:14] frigate.mqtt                   INFO    : MQTT connected                                                                          │
│ [2021-10-31 22:29:14] detector.coral                 INFO    : Starting detection process: 216                                                         │
│ [2021-10-31 22:29:14] frigate.edgetpu                INFO    : Attempting to load TPU as pci:0                                                         │
│ [2021-10-31 22:29:14] ws4py                          INFO    : Using epoll                                                                             │
│ [2021-10-31 22:29:14] frigate.app                    INFO    : Output process started: 218                                                             │
│ [2021-10-31 22:29:14] frigate.app                    INFO    : Camera processor started for corridor_downstairs: 221                                   │
│ [2021-10-31 22:29:14] frigate.app                    INFO    : Capture process started for corridor_downstairs: 222                                    │
│ [2021-10-31 22:29:14] frigate.edgetpu                INFO    : TPU found                                                                               │
│ [2021-10-31 22:29:15] ws4py                          INFO    : Using epoll                                                                             │
│ [2021-10-31 22:53:07] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35686]                │
│ [2021-10-31 22:54:25] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35686]             │
│ [2021-11-01 11:02:20] frigate.mqtt                   INFO    : Turning off detection for corridor_downstairs via mqtt                                  │
│ [2021-11-01 11:02:21] frigate.mqtt                   INFO    : Turning off recordings for corridor_downstairs via mqtt                                 │
│ [2021-11-01 11:02:22] frigate.mqtt                   INFO    : Turning off snapshots for corridor_downstairs via mqtt                               
```
ps aux output
```
root@frigate-558567f6df-q27l9:/# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0    196     4 ?        Ss   Oct31   0:00 s6-svscan -t0 /var/run/s6/services
root          34  0.0  0.0    180     8 ?        S    Oct31   0:00 foreground  if   /etc/s6/init/init-stage2-redirfd   foreground    if     if      s6-ech
root          35  0.0  0.0    196     4 ?        S    Oct31   0:00 s6-supervise s6-fdholderd
root          44  0.0  0.0    176     4 ?        S    Oct31   0:00 foreground  s6-setsid  -gq  --  with-contenv  backtick  -D  0  -n  S6_LOGGING   printco
root         178  0.0  0.0    196     4 ?        S    Oct31   0:00 s6-supervise nginx
root         181  0.0  0.0 581568 13528 ?        Ss   Oct31   0:00 nginx: master process /usr/local/nginx/sbin/nginx
root         194  1.2  0.7 2115796 129280 ?      Sl   Oct31   9:45 python3 -u -m frigate
root         201  0.8  0.2 609216 34744 ?        S    Oct31   6:34 nginx: worker process
root         211  0.0  0.4 734148 65512 ?        S    Oct31   0:02 frigate.logger
root         215  0.1  0.0  14540 11040 ?        S    Oct31   1:03 /usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(29)
root         216  0.1  0.5 949056 90100 ?        Sl   Oct31   1:06 frigate.detector.coral
root         218  0.4  0.4 1011392 75668 ?       Sl   Oct31   3:35 frigate.output
root         221  1.8  0.5 1017380 86340 ?       Sl   Oct31  13:58 frigate.process:corridor_downstairs
root         222  2.3  0.4 1023420 70732 ?       Sl   Oct31  18:03 python3 -u -m frigate
root         230 44.8  0.3 509960 58284 ?        Ssl  Oct31 339:53 ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD12
root         232  0.0  0.0  74620 13220 ?        Ss   Oct31   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720
root         244  0.0  0.0  74620 13192 ?        Ss   Oct31   0:00 ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720
root         247  5.8  0.1  78052 21656 ?        Ss   Oct31  44:22 ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD12
root       14314  0.0  0.0   4240  3712 pts/0    Ss   11:06   0:00 bash
root       14342  0.0  0.0   5900  3088 pts/0    R+   11:07   0:00 ps aux
```
```


### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x559ee26fbb80] max delay reached. need to consume packet
[rtsp @ 0x559ee26fbb80] RTP: missed 6 packets
[rtsp @ 0x559ee26fbb80] max delay reached. need to consume packet
[rtsp @ 0x559ee26fbb80] RTP: missed 8 packets
[rtsp @ 0x559ee26fbb80] max delay reached. need to consume packet
[rtsp @ 0x559ee26fbb80] RTP: missed 2 packets
[rtsp @ 0x559ee26fbb80] max delay reached. need to consume packet
[rtsp @ 0x559ee26fbb80] RTP: missed 5 packets
[h264 @ 0x559ee2702e80] concealing 5243 DC, 5243 AC, 5243 MV errors in I frame
[rtsp @ 0x559ee26fbb80] max delay reached. need to consume packet
[rtsp @ 0x559ee26fbb80] RTP: missed 3 packets
[rtsp @ 0x559ee26fbb80] max delay reached. need to consume packet
[rtsp @ 0x559ee26fbb80] RTP: missed 1 packets
[rtsp @ 0x559ee26fbb80] max delay reached. need to consume packet
[rtsp @ 0x559ee26fbb80] RTP: missed 8 packets
[rtsp @ 0x559ee26fbb80] max delay reached. need to consume packet
[rtsp @ 0x559ee26fbb80] RTP: missed 4 packets
Input #0, rtsp, from 'rtsp://xx.xx.xx.xx:554/s0':
  Metadata:
    title           : s0
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac, 48000 Hz, mono, fltp
    Stream #0:1: Video: h264, yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
```

### Frigate stats

```json
{"corridor_downstairs":{"camera_fps":5.0,"capture_pid":222,"detection_fps":0.0,"pid":221,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.64,"pid":216}},"service":{"storage":{"/dev/shm":{"free":2145.5,"mount_type":"tmpfs","total":2147.5,"used":2.0},"/media/frigate/clips":{"free":18447.5,"mount_type":"ext4","total":21003.6,"used":2539.3},"/media/frigate/recordings":{"free":18447.5,"mount_type":"ext4","total":21003.6,"used":2539.3},"/tmp/cache":{"free":32251.6,"mount_type":"overlay","total":42007.2,"used":7591.4}},"uptime":45602,"version":"0.9.4-26ae608"}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Unifi G3 Flex

**Comment by blakeblackshear** [comment] 2021-11-01 12:44
Duplicate of #1911

**Closed by blakeblackshear** 2021-11-01 12:44 UTC
Labels: support, triage
