### ISSUE TITLE
Click on camera in birdseye to open that camera

### ISSUE THREAD

**Issue by timgurske** [blakeblackshear/frigate#10326] opened 2024-03-08 04:48 UTC
Since the cameras view doesn't update, I use the birdseye view as my default view. If I want to "solo" a camera it would be easiest to be able to click on that camera in the birdseye view and have it open that camera page.

I am assuming that the birdseye view is a actually a video being pieced together so we would have to generate a link map and overlay it onto the video. I would help but I think that I am the only dev who doesn't know Python :-(

**Comment by NickM-27** [comment] 2024-03-08 12:32
We are currently rewriting the UI and in the new UI dashboard all cameras use the live view when motion or objects are detected. 

In any case this is a duplicate of https://github.com/blakeblackshear/frigate/issues/1735

**Closed** 2024-03-08 12:33 UTC
Labels: duplicate, enhancement
