### ISSUE TITLE
[Support]: Ffmpeg process crashed unexpectedly after HassOS Upgrade to 9.3

### ISSUE THREAD

**Issue by Coolie1101** [blakeblackshear/frigate#4266] opened 2022-11-06 16:49 UTC
### Describe the problem you are having

Can't seem to get video feed from cameras after upgrading HassOS, and Ffmpeg crashes.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
mqtt:
  host: 192.168.200.211
  topic_prefix: frigate
  user: hassos
  password: XXXXXXXXXXXXXXXX
  stats_interval: 30

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  width: 1536
  height: 2048
  quality: 1
  mode: objects

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

detect:
  width: 640
  height: 480

record:
  enabled: true
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 30
      mode: active_objects
      objects:
        person: 30

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 30
    objects:
      person: 30

cameras:
### Porch Camera 03
  porch_01:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXXXXXXXXXXXX@192.168.200.61/streaming/channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:XXXXXXXXXXXXXXXX@192.168.200.61/streaming/channels/101
          roles:
            - record

    objects:
      track:
        - person
        - cat
        - dog

    motion:
      mask:
        - 454,127,468,0,640,0,600,176
        - 0,31,42,30,200,411,125,480,0,480
        - 356,201,352,277,260,281,247,189,287,0,468,0,460,118
        - 199,117,0,195,0,0,197,0,366,0,363,150

    zones:
      Door:
        coordinates: 149,480,517,480,261,400
      Porch:
        coordinates: 362,283,299,271,222,341,531,447,572,278,453,179
      Steps:
        coordinates: 223,344,144,319,193,279,311,269
      Yard:
        coordinates: 288,174,132,306,108,206,202,151

    objects:
      filters:
        person:
          mask:
            - 0,0,46,0,164,363,0,480
            - 286,0,274,160,239,228,357,193,459,113,471,0
            - 460,133,474,0,640,0,601,188
            - 59,166,195,105,282,124,294,0,29,0

### South Side Camera 06
  south_side:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXXXXXXXXXXXX@192.168.200.56/streaming/channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:XXXXXXXXXXXXXXXX@192.168.200.56/streaming/channels/101
          roles:
            - record

    objects:
      track:
        - person
        - cat
        - dog

    motion:
      mask:
        - 390,80,379,0,569,0,571,86
        - 0,447,0,480,204,480,198,444

    objects:
      filters:
        person:
          mask:
            - 379,0,391,84,566,86,562,0
            - 398,119,418,118,414,71,393,73
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-11-06 11:33:47] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
[2022-11-06 11:33:47] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-11-06 11:33:47] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-11-06 11:33:47] peewee_migrate                 INFO    : There is nothing to migrate
[2022-11-06 11:33:47] frigate.app                    INFO    : Output process started: 217
[2022-11-06 11:33:47] detector.coral                 INFO    : Starting detection process: 216
[2022-11-06 11:33:47] frigate.app                    INFO    : Camera processor started for porch_01: 219
[2022-11-06 11:33:47] ws4py                          INFO    : Using epoll
[2022-11-06 11:33:47] frigate.app                    INFO    : Camera processor started for south_side: 220
[2022-11-06 11:33:47] frigate.app                    INFO    : Capture process started for porch_01: 222
[2022-11-06 11:33:47] frigate.app                    INFO    : Capture process started for south_side: 223
[2022-11-06 11:33:48] ws4py                          INFO    : Using epoll
[2022-11-06 11:33:47] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-11-06 11:33:50] frigate.edgetpu                INFO    : TPU found
[2022-11-06 11:34:07] watchdog.porch_01              INFO    : No frames received from porch_01 in 20 seconds. Exiting ffmpeg...
[2022-11-06 11:34:07] watchdog.porch_01              INFO    : Waiting for ffmpeg to exit gracefully...
[2022-11-06 11:34:07] watchdog.south_side            INFO    : No frames received from south_side in 20 seconds. Exiting ffmpeg...
[2022-11-06 11:34:07] watchdog.south_side            INFO    : Waiting for ffmpeg to exit gracefully...
[2022-11-06 11:34:37] watchdog.porch_01              INFO    : FFmpeg didnt exit. Force killing...
[2022-11-06 11:34:37] frigate.video                  ERROR   : porch_01: Unable to read frames from ffmpeg process.
[2022-11-06 11:34:37] frigate.video                  ERROR   : porch_01: ffmpeg process is not running. exiting capture thread...
[2022-11-06 11:34:37] watchdog.south_side            INFO    : FFmpeg didnt exit. Force killing...
[2022-11-06 11:34:37] frigate.video                  ERROR   : south_side: Unable to read frames from ffmpeg process.
[2022-11-06 11:34:37] frigate.video                  ERROR   : south_side: ffmpeg process is not running. exiting capture thread...
[2022-11-06 11:34:47] watchdog.porch_01              ERROR   : Ffmpeg process crashed unexpectedly for porch_01.
[2022-11-06 11:34:47] watchdog.porch_01              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-11-06 11:34:47] ffmpeg.porch_01.detect         ERROR   : [flv @ 0x558f180080] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-11-06 11:34:47] watchdog.south_side            ERROR   : Ffmpeg process crashed unexpectedly for south_side.
[2022-11-06 11:34:47] watchdog.south_side            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-11-06 11:34:47] ffmpeg.south_side.detect       ERROR   : [flv @ 0x559f179860] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-11-06 11:35:07] watchdog.porch_01              INFO    : No frames received from porch_01 in 20 seconds. Exiting ffmpeg...
[2022-11-06 11:35:07] watchdog.porch_01              INFO    : Waiting for ffmpeg to exit gracefully...
[2022-11-06 11:35:07] watchdog.south_side            INFO    : No frames received from south_side in 20 seconds. Exiting ffmpeg...
[2022-11-06 11:35:07] watchdog.south_side            INFO    : Waiting for ffmpeg to exit gracefully...
[2022-11-06 11:36:37] watchdog.porch_01              INFO    : FFmpeg didnt exit. Force killing...
[2022-11-06 11:36:37] frigate.video                  ERROR   : porch_01: Unable to read frames from ffmpeg process.
[2022-11-06 11:36:37] frigate.video                  ERROR   : porch_01: ffmpeg process is not running. exiting capture thread...
[2022-11-06 11:36:37] watchdog.south_side            INFO    : FFmpeg didnt exit. Force killing...
[2022-11-06 11:36:37] frigate.video                  ERROR   : south_side: Unable to read frames from ffmpeg process.
[2022-11-06 11:36:37] frigate.video                  ERROR   : south_side: Unable to read frames from ffmpeg process.
[2022-11-06 11:36:37] frigate.video                  ERROR   : south_side: ffmpeg process is not running. exiting capture thread...
[2022-11-06 11:36:47] watchdog.porch_01              ERROR   : Ffmpeg process crashed unexpectedly for porch_01.
[2022-11-06 11:36:47] watchdog.porch_01              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-11-06 11:36:47] ffmpeg.porch_01.detect         ERROR   : [flv @ 0x556d015d70] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-11-06 11:36:47] watchdog.south_side            ERROR   : Ffmpeg process crashed unexpectedly for south_side.
[2022-11-06 11:36:47] watchdog.south_side            ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-11-06 11:36:47] ffmpeg.south_side.detect       ERROR   : [flv @ 0x55b2f23b10] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-11-06 11:37:07] watchdog.porch_01              INFO    : No frames received from porch_01 in 20 seconds. Exiting ffmpeg...
[2022-11-06 11:37:07] watchdog.porch_01              INFO    : Waiting for ffmpeg to exit gracefully...
[2022-11-06 11:37:07] watchdog.south_side            INFO    : No frames received from south_side in 20 seconds. Exiting
```

### FFprobe output from your camera

```shell
ffprobe version 4.1.10-0+deb10u1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --prefix=/usr --extra-version=0+deb10u1 --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --arch=arm --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, rtsp, from 'rtsp://admin:XXXXXXXXXXXXXXXX@192.168.200.56/streaming/channels/102':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.516667, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x480 [SAR 4:3 DAR 16:9], 12 fps, 15 tbr, 90k tbn, 24 tbc
```

### Frigate stats

```json
?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

LTS CMIP3382NW-M

### Any other information that may be helpful

Everything worked great prior to upgrading HassOS.

**Comment by NickM-27** [comment] 2022-11-06 17:10
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3780 recommend reading there

**Closed by NickM-27** 2022-11-06 17:10 UTC
Labels: duplicate, support, triage

**Comment by Coolie1101** [comment] 2022-11-06 19:24
> This is a duplicate of #3780 recommend reading there

Thanks.
