### ISSUE TITLE
Disable Frigate from consuming specifed feed(s) via MQTT and/or WebUI.

### ISSUE THREAD

**Issue by reefland** [blakeblackshear/frigate#2269] opened 2021-11-17 03:37 UTC
**Describe what you are trying to accomplish and why in non technical terms**
When home assistant detects people home, I use MQTT to have all my interior cams swing around and point at the wall so family members and guest don't feel they are being watched. When everyone is gone, the cams swing around and point forward.  Then Frigate does an excellent job doing its motion detection and notification.

I want to reduce CPU cycles and network being consumed by Frigate for the cams pointing at the wall by sending MQTT commands to Frigate to disable/stop consuming PER camera feed.

**Describe the solution you'd like**
Call Service:  `mqtt.publish`
Topic: `frigate/kitchen/enabled/state`
Payload: `OFF`

Frigate would stop processing this feed, perhaps show a static image that the camera feed is off.  Frigate WebUI for the cam should have a toggle to enable again for manual on/off.

When home assistant detects nobody is home, I'll set a Payload 'ON' to indicate the camera feed should be consumed by Frigate.

**Describe alternatives you've considered**
1. Thought about a `docker-compose down` on Frigate, but I don't want to turn off Frigate itself as I want it to still process exterior cameras and I still want to use the WebUI to browse snapshots, recordings, etc.
2. Thought about a dividing Frigate to 2 installations one for exterior, one for interior and stopping one... but that would still prevent me from using the WebUI.
3. I thought setting `frigate/kitchen/detect/state` to OFF would help, but it didn't (didn't see a drop CPU) as Frigate still consumes the video feed. 

**Additional context**
I think there should be a variable set in the `config.yml` to enable this feature per camera (disabled by default).
A GET state could return ON, OFF and perhaps a N/A or empty string if feature is disabled for the specific cam?

**Comment by blakeblackshear** [comment] 2021-11-17 12:53
Duplicate of #1911

**Closed by blakeblackshear** 2021-11-17 12:53 UTC
Labels: enhancement
