### ISSUE TITLE
Apply different object filters depending on whether camera is in day or night (IR) mode

### ISSUE THREAD

**Issue by toxicantidote** [blakeblackshear/frigate#9501] opened 2024-01-30 09:19 UTC
**Describe what you are trying to accomplish and why in non technical terms**
Apply different object filters depending on whether a camera is in day or night mode.

**Describe the solution you'd like**
Frigate to autonomously detect whether a video stream is in colour or monochrome and apply different configured object filters.

**Describe alternatives you've considered**
Usage of area and threshold constraints [per the Frigate docs](https://docs.frigate.video/guides/false_positives/).

**Additional context**
Consider the two snapshots attached, where Frigate has detected a cat in each. Both have approximately the same confidence and area, and are located in a similar place in the frame. However, only one actually contains a cat. The other is a false positive created by a reflector and tyre of a trailer.

![snapshot-1704280849 074006-06vz3f](https://github.com/blakeblackshear/frigate/assets/23189273/c613e312-8d6a-4146-a807-d0a372032190)
![snapshot-1704326304 119841-616bh3](https://github.com/blakeblackshear/frigate/assets/23189273/89b5c170-d5a1-4be4-948d-df3f7aad5ed3)

Now in this case, I do have several obvious solutions:
- Park my trailer better.
- Move the round table so the cat doesn't jump up there.
- Configure an object mask that covers where the wheel usually is.

But, it did get me thinking..
Many cheap cameras have relatively crisp daytime (colour) streams, but present fuzzy night time (monochrome) streams that occasionally confuse the object detection. Further, changes to lighting can also cast shadows that are picked up as objects. We can't really account for dynamic lights (e.g. headlights, handheld lights), but we _could_ account for predictable lights (i.e. the Sun, street lighting).

I think there could be some setups where this would be useful. An alternative could possibly be time-based filters.

Does anybody else see a use in such a feature, and is its implementation worth the development effort?

**Comment by NickM-27** [comment] 2024-01-30 09:30
I’m going to call this a duplicate of https://github.com/blakeblackshear/frigate/issues/2569 since it would be a similar solution regardless. 

Feel free to leave a 👍 and any additional comment.

**Closed** 2024-01-30 17:35 UTC
Labels: duplicate, enhancement
