### ISSUE TITLE
Frigate UI toggles to detect, recordings and snapshots are error prone

### ISSUE THREAD

**Issue by ekt-** [blakeblackshear/frigate#4331] opened 2022-11-09 10:50 UTC
it is very easy to accidentally click on one of the toggles that disable recordings without realizing it, especially from small cell phones display.

the result is that no more clips are recorded, but you discover it many days later, when the recordings would be needed but they are not there.

being able to see the status of the toggles from the ui makes sense.
being able to change its status without going through the configuration makes sense

but changing its status should be more protected. in another window, or upon confirmation, or something else I can't imagine.

**Comment by NickM-27** [comment] 2022-11-09 11:22
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/4206

**Closed** 2022-11-09 11:22 UTC
Labels: duplicate, enhancement

**Comment by ekt-** [comment] 2022-11-09 13:46
yes, sorry, missed it

**Comment by NickM-27** [comment] 2022-11-09 13:54
feel free to leave a 👍 on the issue and any comments on additional thoughts you may have

**Comment by hstr0100** [comment] 2023-08-12 19:15
Has this ever been implemented?

Especially because there's no authentication whatsoever, I feel like those toggles should have a degree of difficulty to activate or be hidden entirely

It also looks a lot like the button used to *view* recordings in similar NVR software, your average non tech savy user who doesn't speak English (Meaning that "Recordings" means nothing to them) is gonna click it and be like "Oh, nothing happened, this must be broken, moving on" and without knowing they would have disabled recordings.

**Comment by NickM-27** [comment] 2023-08-12 19:22
> Has this even been implemented?

There is a pinned PR to add different user modes in the UI https://github.com/blakeblackshear/frigate/pull/6916

> Especially because there's no authentication whatsoever, I feel like those toggles should have a degree of difficulty to activate or be hidden entirely

In general I disagree with this as an absolute statement, I use them on a weekly basis and making them more difficult to get to just makes the UI more cumbersome to use
