### ISSUE TITLE
Filter by time range

### ISSUE THREAD

**Issue by Armadillo1** [blakeblackshear/frigate#4618] opened 2022-12-06 17:43 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to filter recordings by time as am mostly interested in what happens overnight.

**Describe the solution you'd like**
Filter by time. From time x to time y.

**Describe alternatives you've considered**
Scroll and review videos manually.

**Comment by NickM-27** [comment] 2022-12-06 18:04
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3140 and there is also a draft implementation at https://github.com/blakeblackshear/frigate/pull/3302

**Closed by NickM-27** 2022-12-06 18:04 UTC
Labels: duplicate, enhancement
