### ISSUE TITLE
Birdseye Bounding boxes

### ISSUE THREAD

**Issue by sberryman** [blakeblackshear/frigate#8561] opened 2023-11-10 02:58 UTC
**Describe what you are trying to accomplish and why in non technical terms**
What would you think about a flag to enable bounding boxes drawn (detections and/or motion) on Birdseye frames

**Describe the solution you'd like**
I haven't looked through the code on this yet but I'm making a big assumption that the bbox is available on the Birdseye thread? 

**Additional context**
It would be nice to show a point and line plot as well based on N frames of history. Take the bottom center of a detection over N frames and show those point and lines connecting them with an opacity based on age. Would make it easy to visualize why a camera is visible and where the object was over time that triggered it. (This is bonus)

Just floating the idea before I pursue it.

**Comment by NickM-27** [comment] 2023-11-10 03:00
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1910

Feel free to leave a 👍

**Closed by NickM-27** 2023-11-10 03:00 UTC
Labels: duplicate, enhancement

**Comment by sberryman** [comment] 2023-11-10 04:24
Thanks for pointing out the duplication @NickM-27 - that referenced issue is ancient. Doesn't really answer my question. The lift might be large but if the audience is 3 people not worth it. 

If it is bigger I might take a stab at it. I use birdseye as the primary "view" into activity around my home. When a camera suddenly pops up it would be nice to know why. 

Do you have telemetry into birdseye? Is it a fringe feature?

**Comment by NickM-27** [comment] 2023-11-10 11:54
Birdseye is a commonly used feature though this isn't a common request. Also as Blake explained in the issue I linked this will be complicated to support and will reduce the performance of birdseye.
