### ISSUE TITLE
Merge of cameras and Birdseye

### ISSUE THREAD

**Issue by ch1988** [blakeblackshear/frigate#7483] opened 2023-08-15 21:52 UTC
From my point of view, it would be cool to merge "cameras" and "Birdseye" together. 

- cameras show no live stream (hope I setup everything right), but leads me to the detailed view and the events
- Birdseye show a live view, but I can' t "klick" on a camera to see more details. 

So from my point of view, a clickable Birdseye with the features of camera would be a great improvement.

**Comment by NickM-27** [comment] 2023-08-15 21:55
I think this is mostly a duplicate of https://github.com/blakeblackshear/frigate/issues/1735

I think the feature of opening a camera from birdseye makes sense, and potentially a way to view live views on the camera dashboard. 

But the main feature of birdseye is the ability to show cameras only when they detect objects, motion, etc. depending on how you configure it. This would be a jarring experience if you are trying to open a camera that is not currently detecting objects.

**Closed by NickM-27** 2023-08-15 21:55 UTC
Labels: duplicate, enhancement
