### ISSUE TITLE
Record 'Any Motion'

### ISSUE THREAD

**Issue by doug62** [blakeblackshear/frigate#2389] opened 2021-12-06 04:13 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to RECORD ANY MOTION  so that I can ENSURE THAT I CAPTURE ALL EVENTS REGARDLESS OF RECOGNITION QUALITY

**Describe the solution you'd like**
CREATE AN 'OBJECT' - IT SELECTS ANY MOVEMENT - IT THEN RECORDS LIKE ANY OTHER OBJECT

**Describe alternatives you've considered**

**Additional context**

**Comment by blakeblackshear** [comment] 2021-12-06 04:27
Duplicate of #803

**Closed by blakeblackshear** 2021-12-06 04:27 UTC
Labels: enhancement
