### ISSUE TITLE
Scale playback of portrait cameras by browser height instead of width

### ISSUE THREAD

**Issue by RexWheeler** [blakeblackshear/frigate#4051] opened 2022-10-08 23:44 UTC
I would like to be able to view recordings without having to excessively scroll the browser window horizontally or vertically.

Currently when watching event recordings, the image is scaled to the width of the browser. This is appropriate and convenient for video feeds where the camera is in landscape orientation (image wider than it is tall), but when the camera is in portrait orientation (taller than it is wide), the image is still scaled to the narrower width causing the bottom of the image to be cut off. For portrait images I can scroll down to see the bottom half of the image but then the top half is cut off. While I could resize my browser window to be in a similar portrait ratio, when I get the window narrow enough to show the whole video, the left menu disappears.

Ideally the playback image would be scaled to fit within the visible browser window so that the image would 1) maintain original aspect ratio, and 2) be as large a possible, without cutting off (or requiring scrolling to see) either the right or bottom part of the image.

An alternate solution would be to be able to specify per camera some sort of scaling factor to use when replaying video in the browser. This scaling factor would be used to set the window size of the player object in the browser. (I am not suggesting a transcode pass prior to playback.)

Sample view of top half of video (note you have to scroll down to get to the play/pause controls):
![portrait_top](https://user-images.githubusercontent.com/6587943/194731141-250a024e-409a-4ea7-b374-c285138623fe.jpg)

Sample view of bottom half of video:
![portrait_bottom](https://user-images.githubusercontent.com/6587943/194731140-c939e4df-8073-45f6-9f82-dd4358f82c7f.jpg)

If you make the window really tall and narrow you can see the whole thing, but you lose the left menu:
![portrait_tall_no_menu](https://user-images.githubusercontent.com/6587943/194731139-60f62881-a64e-4ddc-9070-722860934f0b.jpg)

**Comment by NickM-27** [comment] 2022-10-08 23:45
What version of frigate are you running?

**Comment by RexWheeler** [comment] 2022-10-08 23:48
Build that was just released: 0.11.1-2EADA21 (thanks)

**Comment by NickM-27** [comment] 2022-10-08 23:53
I think this should be as simple as setting a max height, similar to https://github.com/blakeblackshear/frigate/issues/3287

**Comment by TheDescender** [comment] 2023-09-07 19:13
Am I understanding correctly that this still isn't resolved? Or is there some way to set recording player size in the config as we can set the live view?

As it stands this is my recording player size. The bottom half of the image and the player controls are cut-off. ![image](https://github.com/blakeblackshear/frigate/assets/43969610/95a68e1d-493a-4c65-9087-5f6e5fa308ea) 

Likely caused by the camera having a 2560x1920 resolution. As a result I can never view recordings while having my browser fullscreen. Any action besides manually resizing my browser doesn't really help at all.

**Comment by NickM-27** [comment] 2023-09-07 19:22
@TheDescender for one, this request has to do with the events viewer not 24/7 recording playback.

In this case you can scroll down to find the full screen button. This screen will be redesigned to solve issues like these in the future

**Comment by TheDescender** [comment] 2023-09-07 20:21
Ok thanks for the info. As long as this is something still being worked on and not something I was overlooking in the docs, I'm fine.

I just decided to pose the question here since this was the first open topic with the exact issue in the title which doesn't mention the events viewer specifically. I read earlier comments of yours in another topic that this was being worked on, but that was from 2022. I don't know the dev timeline.

**Comment by matiasba** [comment] 2023-12-05 14:44
Just to update on this. This is still a problem in the latest stable 0.12.1, portrait cameras are very difficult to see on the event viewer or the camera list. 
![image](https://github.com/blakeblackshear/frigate/assets/15465574/e865a75e-edad-4af3-9b40-1748629bf436)

**Comment by TheSleepySlee** [comment] 2023-12-27 07:31
Still an issue in frigate:0.13.0-beta7 too, but as long as this ticket is open, seems normal :)

- In the bridseye, my portrait cam is in 3rd position (out of 5), on first row (3 on first row, 2 in last row), and image is distorted.
- Similar as on the cameras page, image is distorded
- When going on the portrait camera page, the image is similar as comments above, with width being selected for fullscreen instead of height, which causes the scrolling need.

**Comment by NickM-27** [comment] 2024-03-15 21:05
this is generally covered in https://github.com/blakeblackshear/frigate/issues/5449 and has been implemented as part of the new UI rewrite, closing

**Closed by NickM-27** 2024-03-15 21:05 UTC
Labels: enhancement, pinned
