### ISSUE TITLE
Review page URL should include event ID

### ISSUE THREAD

**Issue by edalquist** [blakeblackshear/frigate#13639] opened 2024-09-09 17:51 UTC
I want to be able to deep link and share links to specific events.

When I click on an event I would like the URL for the page to include the event ID so I can share a link to that view with someone else with access or deep link to events. For example I could have my notification from Home Assistant directly link to the Frigate WebUI review page for the event that triggered the alert.

Example potential URL: https://frigate.example.com/review?id=1725895698.233485-2wdl0x

**Comment by NickM-27** [comment] 2024-09-09 18:01
It doesn't make sense for the url to have an ID. You are inserting yourself into the recordings view at the time of that event but you're not restricted to that event. 

In any case, this is a duplicate of https://github.com/blakeblackshear/frigate/issues/6416

**Closed** 2024-09-09 18:02 UTC
Labels: duplicate, enhancement
