### ISSUE TITLE
[Support]: Frigate proxy addon doesnt install on Home Assistant

### ISSUE THREAD

**Issue by diedvdyk** [blakeblackshear/frigate#5337] opened 2023-02-01 20:41 UTC
### Describe the problem you are having

Installation of the proxy addon gives errors on Home Assistant .
I am running HAOS on a raspberry pi 4, frigate on a Odyssee Blue (that works).
Home Assistant version information
Home Assistant 2023.1.7
Supervisor 2023.01.1 
Operating System 9.5 
Frontend 20230110.0 - latest  

### Version

1.3

### Frigate config file

```yaml
not relevant
```

### Relevant log output

```shell
23-02-01 21:30:06 INFO (SyncWorker_4) [supervisor.docker.addon] Starting build for ccab4aaf/aarch64-addon-frigate-proxy:1.3
23-02-01 21:36:25 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build ccab4aaf/aarch64-addon-frigate-proxy:1.3: The command '/bin/bash -o pipefail -c apt-get -qq update     && apt-get -qq install --no-install-recommends -y nginx     && (apt-get autoremove -y; apt-get autoclean -y)' returned a non-zero code: 100
23-02-01 21:36:25 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
Step 1/19 : ARG BUILD_ARCH
Step 2/19 : FROM ghcr.io/hassio-addons/debian-base/${BUILD_ARCH}:5.1.0
 ---> d12f6ecaa0f2
Step 3/19 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> 36f2759d4c08
Step 4/19 : RUN apt-get -qq update     && apt-get -qq install --no-install-recommends -y nginx     && (apt-get autoremove -y; apt-get autoclean -y)
 ---> Running in 5f09b2713e40
E: Failed to fetch http://deb.debian.org/debian/pool/main/libb/libbsd/libbsd0_0.11.3-1_arm64.deb  Connection timed out [IP: 199.232.150.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/i/iproute2/iproute2_5.10.0-4_arm64.deb  Connection timed out [IP: 199.232.150.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/t/tiff/libtiff5_4.2.0-1%2bdeb11u3_arm64.deb  Connection timed out [IP: 151.101.2.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/i/icu/libicu67_67.1-7_arm64.deb  Connection timed out [IP: 199.232.150.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Removing intermediate container 5f09b2713e40
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

I checked the connection timeout errors by doing ssh into HAOS.
A wget from the files goes well and the debian files are fetched.
So the timeout errors must be caused by another problem then internet connectivity.

**Comment by NickM-27** [comment] 2023-02-01 20:43
To me this seems like a supervisor error not anything to do with frigate itself. If it can't get those files then it's something not connecting in HA OS

**Comment by diedvdyk** [comment] 2023-02-01 20:48
All other addons install well, so my supervisor doesnt have any problem.
There must be something wrong with the debian docker image.
Maybe there have been some upgrades of the packages ?
Where can I download the source of the proxy addon, so that I can have a look myself ?

**Comment by NickM-27** [comment] 2023-02-01 20:52
> All other addons install well, so my supervisor doesnt have any problem.

that doesn't really hold water. There are plenty of cases where a supervisor issue can only affect some addons and not others.

> Where can I download the source of the proxy addon, so that I can have a look myself ?

That is on a different repo https://github.com/blakeblackshear/frigate-hass-addons

**Comment by diedvdyk** [comment] 2023-02-01 21:00
In that repo in an issue regarding the same , see 
https://github.com/blakeblackshear/frigate-hass-addons/issues/86
So I am not the only one having this issue

**Comment by NickM-27** [comment] 2023-02-01 21:03
okay, will close this issue as it is a duplicate of that and can continue discussion over there

**Closed by NickM-27** 2023-02-01 21:03 UTC
Labels: duplicate, support, triage
