### ISSUE TITLE
[Feature Request]: Zoom specific camera in Birdseye

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5511] opened 2023-02-15 23:24 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to quickly get to the full resolution and/or debug views of a single camera very quickly when it shows up in Birdseye.

**Describe the solution you'd like**
When a Camera is showing in Birdseye, instead of going full-screen of Birdseye, go to the specific camera page for the particular camera that was clicked. This works fantastic in group stream camera with Blue Iris' web UI, so I know it's possible. I _don't_ know if Frigate provides the necessary data to the frontend about which cameras are currently included in Birdseye, at which locations.

**Comment by NickM-27** [comment] 2023-02-15 23:37
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/1735

**Closed by NickM-27** 2023-02-15 23:37 UTC
Labels: duplicate, enhancement
