### ISSUE TITLE
Feature To enable/disable Camera throuth MQTT / And a User Password Authentication

### ISSUE THREAD

**Issue by newwebform** [blakeblackshear/frigate#8939] opened 2023-12-12 17:45 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to active disabled camera in config through frigate integration  so that I can lower my cpu usage on camera that i don't want at specific time off day.  

----
please add a simple user pass to api and all port exposed i run this through docker in windows and it expose to all lan i use firewall to block access to port from the ip that i don't want but having a simple user pass authentication won't hurt and it will be very beneficial.

**Comment by NickM-27** [comment] 2023-12-12 17:48
This is a duplicate of #1911

**Closed** 2023-12-12 17:48 UTC
Labels: duplicate, enhancement
