### ISSUE TITLE
Add easy way to run clip through existing camera settings to debug

### ISSUE THREAD

**Issue by cliffjao** [blakeblackshear/frigate#4246] opened 2022-11-03 18:19 UTC
To debug & tweak settings on my "driveway_cam", I currently have to do this:
1. Download clip to my computer
2. Upload clip to a volume that is mounted in Docker on my server
3. Edit Frigate config settings for my "test_cam" that mirrors the settings of my "driveway_cam"
4. When I'm happy with the settings, copy them back over to "driveway_cam"
5. Remove/comment out "test_cam" settings until the next time I need to do this again

Would be great if there was a 1-click interface for any event clip to send back through the camera debug to analyze what was going on.

**Comment by NickM-27** [comment] 2022-11-03 18:20
This seems like a duplicate of https://github.com/blakeblackshear/frigate/issues/3856

**Closed** 2022-11-07 22:23 UTC
Labels: duplicate, enhancement
