### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by sharkssl** [blakeblackshear/frigate#3169] opened 2022-04-30 05:42 UTC
### Describe the problem you are having

Hello, I used to run frigate then uninstalled it.
I re-installed it, configuration not changed, same version 3.1, and now it's not even starting.

### Version

Home Assistant 2022.4.7; Frigate NVR Current version: 3.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.25
  user: mqttuser
  password: ...

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
   
cameras:
  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:...@192.168.1.10:554/cam/realmonitor?channel=2&subtype=0
          roles:
            - detect
            - clips
            - record
            - rtmp
   detect:
     width: 928
      height: 576
      fps: 5  
      objects:
        track:
          - person
  cam4:
    ffmpeg:
      inputs:
        - path: rtsp://admin:...@192.168.1.10:554/cam/realmonitor?channel=4&subtype=0
          roles:
            - detect
            - clips
            - record
            - rtmp
    detect:
      width: 928
      height: 576
      fps: 5  
      objects:
        track:
          - person

snapshots:
   enabled: True
   timestamp: True
   retain:
     default: 3
```

### Relevant log output

```shell
no log!
```

### FFprobe output from your camera

```shell
[core-ssh ~]$ ffprobe version 4.4.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.3.1 (Alpine 10.3.1_git20210424) 20210424
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --enable-vulkan --enable-libsoxr --enable-libwebp --enable-libaom --disable-debug
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0  libswscale      5.  9.100 /  5.  9.100  libswresample   3.  9.100 /  3.  9.100  libpostproc    55.  9.100 / 55.  9.100[rtsp @ 0x7f88729670] method DESCRIBE failed: 404 Not Foundrtsp://admin:...@192.168.1.10:554/cam/realmonitor?channel=2: Server returned 404 Not Found
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

analog cameras connected to a Dahua NVR

### Any other information that may be helpful

used to work!

**Comment by NickM-27** [comment] 2022-04-30 12:11
We need the log from supervisor to be able to see what the issue is.

For one, there is no clips robe so that should be removed.

**Comment by sharkssl** [comment] 2022-05-14 21:00
here is the log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-05-14 22:59:29] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
while parsing a block mapping
  in "<unicode string>", line 25, column 3:
      cam2:
      ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 33, column 4:
       detect:
       ^
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 900, in parse_file
    config = yaml.safe_load(raw_config)
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 25, column 3:
      cam2:
      ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 33, column 4:
       detect:
       ^
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by NickM-27** [comment] 2022-05-14 21:04
It is complaining of an invalid confi, In your config `detect` is only indented 3 spaces instead of 4

**Comment by sharkssl** [comment] 2022-05-14 21:07
wow, fast reply! thanks

**Comment by sharkssl** [comment] 2022-05-14 21:15
now works, it was a subtle error... thanks again

**Comment by NickM-27** [comment] 2022-05-14 21:16
Glad to hear it. Now that it's working feel free to close this 👍

**Closed** 2022-05-14 21:26 UTC
Labels: support, triage
