### ISSUE TITLE
Limiting users to specific cameras

### ISSUE THREAD

**Issue by Swedlund** [blakeblackshear/frigate#12923] opened 2024-08-10 11:02 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to limit a user to a camera or a group of cameras

**Describe the solution you'd like**
For example, in the UI go to Settings -> Users. Create a user or edit an existing user. Checkbox the cameras or camera groups shown in a list. The selected cameras will only be accessible for this user to view and review footage from.

**Describe alternatives you've considered**
Same as above but without UI. Restrictions are instead set directly in the configuration file

**Additional context**
I have two sites with cameras. There are users who should be able to see both sites but there are also users who need to be restricted to seeing cameras from only one site

**Comment by NickM-27** [comment] 2024-08-10 12:37
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/6614

**Closed by NickM-27** 2024-08-10 12:37 UTC
Labels: duplicate, enhancement
