### ISSUE TITLE
Feature Request: Remove Oldest Clips When SizeInGB Limit Reached

### ISSUE THREAD

**Issue by utkarshjain00** [blakeblackshear/frigate#1311] opened 2021-07-01 05:34 UTC
As I understand, Frigate allows to keep last N days of clips and removes older clips automatically from its database and disk.

In most cases, this works fine as one could extrapolate disk used and keep some extra room. Except when it doesn't like someone was working outside all day and created a ton of clips. 

My request is to create an option limit clips storage to  X GB, and delete oldest clips if the size limits hits. Basically, guarantee that storage will never go over that limit. 

I can do it with scripts and delete files, but that will leave entries in database and ideally this should be handled by Frigate. Please consider. Thanks.

**Comment by blakeblackshear** [comment] 2021-07-01 11:40
Duplicate of #994

**Closed by blakeblackshear** 2021-07-01 11:40 UTC
