### ISSUE TITLE
Mqtt activation available from UI

### ISSUE THREAD

**Issue by kris969** [blakeblackshear/frigate#15654] opened 2024-12-23 12:45 UTC
A lot of configuration improvements, directly available from UI, have been add, that's great!
Camera Settings, zones and objects, are now really more simple to set than before.

When many cameras, zones and objects are used, needs for mqtt are in general for few of them.
Don't you think it could be useful to be able to toggle mqtt activation from UI,  based on camera, zone and object?

The basic mqtt configuration should have to be set in config yml file, only toggling activation, for previous listed criteria, should be set from UI, of course it will set the relative settings in config yml file in camera's section.

Many thanks to the community having done a such great job!
Regards

**Comment by NickM-27** [comment] 2024-12-23 12:48
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/5473

**Closed** 2024-12-23 12:48 UTC
Labels: duplicate, enhancement

**Comment by NickM-27** [comment] 2024-12-23 12:50
Also, regarding the per camera, no I don't think it makes sense to only use mqtt for some cameras. There's no harm in having MQTT topics that are not used.
