### ISSUE TITLE
Snapshot using the best resolution image

### ISSUE THREAD

**Issue by DrSpaldo** [blakeblackshear/frigate#5738] opened 2023-03-15 21:56 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have the snapshot in the highest resolution possible. Currently they are taking the snapshot from the detection stream, which is the low res (secondary feed).

**Describe the solution you'd like**
The screenshot be pulled from the highest resolution (main feed) like the recording does.

**Describe alternatives you've considered**
NA

**Additional context**
Hopefully I haven't missed this option, as I searched the docs and there were no reference to change where the snapshot was pulled from.

**Comment by blakeblackshear** [comment] 2023-03-15 22:41
Duplicate of #2199

**Closed by blakeblackshear** 2023-03-15 22:41 UTC
Labels: enhancement
