### ISSUE TITLE
Ability to lock toggles on the webUI

### ISSUE THREAD

**Issue by kulmosen** [blakeblackshear/frigate#5580] opened 2023-02-24 09:11 UTC
**Describe what you are trying to accomplish and why in non technical terms**
When using Frigate with a mobile device, it is very easy to toggle the enable/disable Events and Recordings. Often this disables part of Frigate, and during troubleshooting its not the first thing to look for. I often end up slapping my forehead and saying "Doh". :-)

**Describe the solution you'd like**
The ability to activate or deactivate the toggles in the WebUI. Its not needed to remove them, because they still indicate the state of the camera. But it would be great if you could lock the on/off state in the config file. Like when record: enabled: False you can not enable it in UI. So it would be great if there where an option like record: enabled: True which can not be disabled in the UI.

**Describe alternatives you've considered**
I cant think of any alternatives.

**Additional context**
![Screenshot_20230224_100557_io homeassistant companion android](https://user-images.githubusercontent.com/10152058/221138592-fb630990-093c-445a-b3b3-908a81e597fe.jpg)

**Comment by NickM-27** [comment] 2023-02-24 12:47
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3539

Feel free to leave comments there and leave a 👍 to show support for the request

**Closed** 2023-02-24 12:47 UTC
Labels: duplicate, enhancement
