### ISSUE TITLE
Adding Go2RTC support for Frigate Proxy

### ISSUE THREAD

**Issue by wes1993** [blakeblackshear/frigate#7398] opened 2023-08-05 09:05 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to access the Go2RTC config page from frigate accessed by the Frigate Proxy Addon in Homeassistant. 

**Describe the solution you'd like**
Adding the Go2RTC support in Frigate Addon

**Describe alternatives you've considered**
No one.

**Additional context**
Accessing now i have this error:
![image](https://github.com/blakeblackshear/frigate/assets/52070589/6fff7d29-4227-45f9-831e-49d1f8e7e579)

The path when i click on Go2RTC Dashboard:
/live/webrtc/

**Comment by NickM-27** [comment] 2023-08-05 11:23
This is the wrong repo for the request and duplicate of https://github.com/blakeblackshear/frigate-hass-addons/issues/124

**Closed** 2023-08-05 11:23 UTC
Labels: duplicate, enhancement
