### ISSUE TITLE
Send to Frigate+ Modal handling

### ISSUE THREAD

**Issue by baldisos** [blakeblackshear/frigate#10940] opened 2024-04-11 15:27 UTC
**Describe what you are trying to accomplish and why in non technical terms**
When trying to send multiple events to Frigate+, you always have to wait for the Send-Modal to disappear.
When closing the first modal and trying to send another one, the other modal gets closed too.
Waiting for the modal to close takes about 4-5 seconds in my case, so it gets a bit tedious when sending a couple of events.

**Describe the solution you'd like**
If it is the upload that takes time to complete, maybe we can run it in the background?
If it is for another reason maybe the original modal can be somewhat decoupled from other ones, so that closing one doesn't interfere with others?

**Comment by NickM-27** [comment] 2024-04-11 15:31
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/10491

an improved flow has already been implemented for the next version of frigate

**Closed by NickM-27** 2024-04-11 15:31 UTC
Labels: enhancement
