### ISSUE TITLE
Addon not starting after upgrade

### ISSUE THREAD

**Issue by B0ndo2** [blakeblackshear/frigate#9535] opened 2024-01-31 18:51 UTC
### Describe the problem you are having

I upgraded to v0.13 today and it is failing to start with this error message
Can't create container from addon_ccab4aaf_frigate: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate: Bad Request ("invalid CapAdd: unknown capability: "CAP_PERFMON"")

### Version

0.13

### Frigate config file

```yaml
Not relevant as it is not starting
```

### Relevant log output

```shell
No logs, not starting
```

### FFprobe output from your camera

```shell
Not starting
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Not relevant

**Comment by NickM-27** [comment] 2024-01-31 18:52
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/9527

**Closed by NickM-27** 2024-01-31 18:52 UTC
Labels: support, triage

**Comment by B0ndo2** [comment] 2024-01-31 19:00
It is not a duplicate, this is not Debian. I am running HassOS

**Comment by NickM-27** [comment] 2024-01-31 19:13
it is the same issue and it is easier for us to track it in one place. Please provide additional info there like version of HA OS

**Comment by B0ndo2** [comment] 2024-01-31 19:19
I was running an older version of HassOS. Upgrading to 10.5 fixed the issue

**Comment by NickM-27** [comment] 2024-01-31 19:20
ah okay thanks for that info
