### ISSUE TITLE
Possibility to switch the detection on certain objects 

### ISSUE THREAD

**Issue by moskovskiy82** [blakeblackshear/frigate#10767] opened 2024-04-01 07:08 UTC
Currently we can only globally disable the detection. It would be great to have a possibility to disable/enable detection on certain objects (person, car e.t.c) on different cameras on the fly.

**Comment by NickM-27** [comment] 2024-05-10 15:53
just realized this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2329

**Closed by NickM-27** 2024-05-10 15:53 UTC
Labels: duplicate, enhancement
