### ISSUE TITLE
Ability to star / favorite clips and they aren’t deleted

### ISSUE THREAD

**Issue by NickM-27** [blakeblackshear/frigate#2555] opened 2022-01-01 00:20 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to favorite / star snapshots / clips in the UI so that I can keep certain clips from being automatically deleted. I could move them elsewhere and have them saved. But I'd like to have it be a first party solution if possible. 

**Describe the solution you'd like**
Recordings are cleared after the retain period expires, I'd like there to be a button in the UI to star or favorite certain recordings and snapshots to not be deleted unless I do so manually. 

**Describe alternatives you've considered**
I know I could move the files to another folder and have them saved but it's nice to have the frigate solution as then they're still viable in get frigate card, media browser, etc in HA

**Comment by blakeblackshear** [comment] 2022-01-01 00:52
duplicate of #615

**Closed by blakeblackshear** 2022-01-01 00:52 UTC
Labels: enhancement
