### ISSUE TITLE
Maximum disk space allocation

### ISSUE THREAD

**Issue by jb773** [blakeblackshear/frigate#3988] opened 2022-09-30 19:45 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to configure Frigate to automatically delete oldest clips/snapshots so that I can stay within a user-specified disk space limit.

**Describe the solution you'd like**
Frigate already allows me to configure maximum retention periods either globally or on a per-camera basis. However, recorded events can often exceed storage space limits which causes Frigate to then crash and stop running altogether. Ideally, I would be able to set a limit (globally and/or per-camera) which would allow a maximum amount of space that clips or snapshots can take up on the disk. This hard limit would take precedence over the retention periods specified in config. Instead of running out of space, it would delete the oldest files in order to make room for new ones.

This is in line with functions that some other NVR software i.e. Blue Iris already sets. For each recording location you can specify a maximum number of days of footage AND a maximum amount of disk space. It will roll off oldest footage if it exceeds X number of days or Y amount of disk space in order to make room for new footage.

**Describe alternatives you've considered**
I have allocated Frigate enough disk space to stay within the bounds of my retention period without running out of space. This works somewhat well but since activity can vary widely on my cameras, it often causes me to run out of space if a camera generates a larger than expected amount of events.

**Comment by NickM-27** [comment] 2022-09-30 19:48
This is a duplicate of #994

**Closed** 2022-09-30 19:48 UTC
Labels: duplicate, enhancement
