### ISSUE TITLE
Disable camera on the fly

### ISSUE THREAD

**Issue by gvillo** [blakeblackshear/frigate#15658] opened 2024-12-23 16:35 UTC
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to disable the camera on the fly via Home Assistant because I have a Zigbee switch to turn on/off the camera for privacy (camera is in the patio). So my idea is to automate that process using HA but I am getting tons of logs regarding the camera if I turn it off using the smart switch (currently there is no other way to turn off video in Reolink cameras)

**Describe the solution you'd like**
The best solution will be disable the camera without the need of edit the configuration file and restart Frigate. Adding a toggle to enable/disable the camera in Configuration section in HA will be the ideal solution

**Describe alternatives you've considered**
Currently, I don't have any alternative

**Additional context**
Ongoing logs if Camera is offline
![image](https://github.com/user-attachments/assets/446f91c2-3f2d-4ba9-b356-18fe482e8150)

I was able to reduce some of the logs by turning off all of these (but Frigate keeps trying to connect, because camera is enabled in the config)
![image](https://github.com/user-attachments/assets/65b01fc3-f4e0-4079-a949-060f155717fe)

**Comment by NickM-27** [comment] 2024-12-23 16:36
This is a duplicate of #1911

**Closed by NickM-27** 2024-12-23 16:36 UTC
Labels: duplicate, enhancement

**Comment by gvillo** [comment] 2024-12-23 17:09
@NickM-27 ohh sorry about that! please close this one. Thank you and happy holidays!
