### ISSUE TITLE
Turn on and off tracking and camera with mqtt 

### ISSUE THREAD

**Issue by alekslyse** [blakeblackshear/frigate#242] opened 2020-10-13 22:52 UTC
To save resources it would be great to be able to turn on tracking on a camera with for example 5-30 seconds pre buffer on external event detection. That way I could save massive resources by starting and stopping detection when I need it. Sometimes I just need proper video detection for 30 seconds or to nothing is detected anymore.

In other words I detected motion on general app, start frigate. Frigate start detection with precache (5-30seconds) before the trigger and stops when no more detection or another mqtt command stops detection

**Comment by blakeblackshear** [comment] 2020-10-13 23:41
What does your setup look like? I use less than a single core to process 7 1080p feeds 24/7 on an i3 NUC. Frigate shouldn't require massive resources when configured properly. The resources required are a mix of ffmpeg decoding, motion detection, and frame processing. Most of the CPU usage is in ffmpeg, so to get a meaningful benefit, I would need to stop decoding altogether. Frigate relies on motion detection to know where to look for objects. By the time the ffmpeg process starts and motion detection establishes a baseline, the event will have passed. Processing a cache after the fact isn't really the use case frigate was built for.

**Comment by blakeblackshear** [comment] 2020-10-13 23:44
This is a duplicate of #16

**Comment by alekslyse** [comment] 2020-10-14 00:27
But would not the detection itself use more resources. If the camera is just idling without running detection before turning on, would that not save resources?

I’m running it on a i3 nuc with a coral so it’s not really a resource issue this far. Mainly I just need detection on 3-4 cameras, but for example I don’t need detection on inside cameras when the house is in home mode.

I admit I don’t know how much it would save of resources just asking:)

Regarding the cache, isn’t frigate intend to detect objects with a live video instead of the one shot alternatives like doods? For me I fully support that function as I don’t see the point in one shot object detection. What I meant was if cameras is streaming, but not using resources for detection before it’s needed that way it can start a second it two before the notification is received from mqtt (as it usually take a couple of seconds from nvr detect a motion before the motion detection tool get it)

**Comment by blakeblackshear** [comment] 2020-10-14 01:35
Frigate already doesn't perform object detection when there is no motion. It is effectively idling when there is no motion and you will see the detection_fps stay at 0. The only thing I can do to reduce CPU usage further would be to reduce decoding. The motion detection I implemented is already very efficient. There is a new feature in ffmpeg that may allow me to dynamically reduce the frame rate or something else when no motion has been detected. That would be the best way to further reduce the "idle" CPU usage.

**Comment by cben0ist** [comment] 2021-01-21 03:05
@blakeblackshear I believe this one can be closed since RC1 release. Working perfectly to me in RC2 now!

**Closed** 2021-01-21 03:05 UTC
